[fork.system]
ForkChainParamV1=110000
ForkChainParamV2=1692674
ForkCheckTxDup=75260
ForkBlockHash=209186
ForkMinerTime=350000
ForkTransferExec=408400
ForkExecKey=408400
ForkWithdraw=480000
ForkTxGroup=408400
ForkResetTx0=453400
ForkExecRollback=706531
ForkTxHeight=806578
ForkCheckBlockTime=1200000
ForkMultiSignAddress=1298600
ForkStateDBSet=1572391
ForkBlockCheck=1560000
ForkLocalDBAccess=1572391
ForkTxGroupPara=1687250
ForkBase58AddressCheck=1800000
# 这个fork只影响平行链，注册类似user.p.x.exec的driver，新开的平行链设为0即可，老的平行链要设置新的高度
ForkEnableParaRegExec=0
ForkCacheDriver=2580000
ForkTicketFundAddrV1=3350000
ForkRootHash=4500000
ForkFormatAddressKey=0
ForkCheckEthTxSort=0
ForkProxyExec=0

[fork.sub.none]
ForkUseTimeDelay=0

[fork.sub.coins]
Enable=0
ForkFriendExecer=0
[fork.sub.manage]
Enable=120000
ForkManageExec=400000
ForkManageAutonomyEnable=10000000
