Title="chain33"
TestNet=false

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 300
# 最多保存的历史日志文件个数
maxBackups = 100
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
dbCache=64
isStrongConsistency=true
singleMode=true
batchsync=false

[p2p]
seeds=["114.55.149.144:13802","139.224.19.175:13802","139.224.82.165:13802"]
enable=true
isSeed=true
serverStart=true
innerSeedEnable=false
useGithub=false
innerBounds=300
msgCacheSize=10240
driver="leveldb"
dbPath="datadir/addrbook"
dbCache=4
grpcLogFile="grpc33.log"
version=15
verMix=15
verMax=16

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]

[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
# 共识驱动名,支持solo/raft/ticket/tendermint/pbft
name="raft"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
# =============== raft共识配置参数 ===========================
# 共识节点ID，raft共识用到，不同的节点设置不同的nodeId（目前只支持1，2，3这种设置）
nodeId=1
# raft共识用到，通过这个端口进行节点的增加和删除
raftApiPort=9121
# raft共识用到，指示这个节点是否新增加节点
isNewJoinNode=false
# raft共识用到，指示raft集群中的服务器IP和端口
peersURL="http://114.55.149.144:9021,http://139.224.19.175:9021,http://139.224.82.165:9021"
# raft共识用到，指示raft集群中只读节点的IP（只同步日志，不参与raft共识）
readOnlyPeersURL=""
addPeersURL=""
#raft共识用到，默认raft中多少条记录打包一个snapshot
defaultSnapCount=1000
# =============== raft共识配置参数 ===========================
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
name="kvdb"
driver="leveldb"
dbPath="datadir/kvdb"
dbCache=128

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
dbCache=16
signType="secp256k1"
minerdisable=true

[exec]
isFree=true
minExecFee=0
