image: chain33-build:latest

before_script:
    - export GO_PROJECT_NAMESPACE="$GOPATH/src/gitlab.33.cn/$CI_PROJECT_NAMESPACE"
    - echo $GO_PROJECT_NAMESPACE
    - mkdir -p $GO_PROJECT_NAMESPACE
    - ln -srf $(pwd) $GO_PROJECT_NAMESPACE
    - export GO_PROJECT_PATH="$GO_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - echo $GO_PROJECT_PATH
    - cd $GO_PROJECT_PATH
    - make clean

after_script:
    - make clean

stages:
    - build
    - test

go_lint:
    stage: build
    script:
        - make linter

go_build_chain33:
    stage: build
    script:
        - make build

go_build_cli:
    stage: build
    script:
        - make cli

go_test:
    stage: test
    script:
        - make test