before_script:
    - export GO_PROJECT_NAMESPACE="$GOPATH/src/gitlab.33.cn/$CI_PROJECT_NAMESPACE"
    - echo $GO_PROJECT_NAMESPACE
    - mkdir -p $GO_PROJECT_NAMESPACE
    - ln -srf $(pwd) $GO_PROJECT_NAMESPACE
    - export GO_PROJECT_PATH="$GO_PROJECT_NAMESPACE/$CI_PROJECT_NAME"
    - echo $GO_PROJECT_PATH
    - cd $GO_PROJECT_PATH
    - make clean

after_script:
    - make clean

stages:
    - build
    - test

go_fmt:
    stage: build
    tags:
        - 33cn
    script:
        - make checkgofmt

go_lint:
    stage: build
    tags:
        - 33cn
    script:
        - make lint

go_build:
    stage: build
    tags:
        - 33cn
    script:
        - make build

go_build_cli:
    stage: build
    tags:
        - 33cn
    script:
        - make cli

go_test:
    stage: test
    tags:
        - 33cn
    script:
        - go test -parallel 1 -race $(go list ./... | grep -v "vendor" | grep -v "chain33/test")
        - cd ~

#go_vet:
#    stage: test
#    script:
#        - go vet $(go list ./... | grep -v "vendor")

#staticcheck:
#    stage: test
#    script:
#        - go get -u honnef.co/go/staticcheck/cmd/staticcheck
#        - staticcheck $(go list ./... | grep -v "vendor")

#gosimple:
#    stage: test
#    script:
#        - go get -u honnef.co/go/simple/cmd/gosimple
#        - gosimple $(go list ./... | grep -v "vendor")
