{ "branches": [ "master", "next" ],
  "plugins": [
    [
        "@semantic-release/commit-analyzer",
      {
        "preset": "jshint"
      }
    ],
    [
        "@semantic-release/release-notes-generator",
      {
        "preset": "jshint"
      }
    ],
    [
        "semantic-release-replace-plugin",
      {
        "replacements": [
          {
            "files": [ "common/version/version.go" ],
            "from": "var Version.*",
            "to": 'var Version = "${nextRelease.version}"',
            "results": [
              {
                "file": "common/version/version.go",
                "hasChanged": true,
                "numMatches": 1,
                "numReplacements": 1
              }
            ],
            "countMatches": true
          }
        ]
      }
    ],
    [
        "@semantic-release/changelog",
        { "changelogFile": "CHANGELOG.md", "changelogTitle": "changelog" },
    ],
    # "@semantic-release/npm", #Default 3
    # "@semantic-release/github", #Default 4
    [
        "@semantic-release/github",
        { "assets": [ "build/*.tar.gz","build/*.zip" ] }
    ],
    [
        "@semantic-release/git",
      {
        "assets": [ "common/version/version.go","CHANGELOG.md" ],
      }
    ],
    [
        "@semantic-release/exec", {
      "prepareCmd": "make all-arch VERSION=${nextRelease.version}"
    }
    ]
  ]
}
