language: go
go_import_path: github.com/33cn/chain33
sudo: false
notifications:
  email: false
jobs:
  include:
    - stage: test
      sudo: require
      install:
        - go get -u golang.org/x/tools/cmd/goimports
        - go get -u gopkg.in/alecthomas/gometalinter.v2
        - gometalinter.v2 -i
        - go get -u mvdan.cc/sh/cmd/shfmt
        - go get -u mvdan.cc/sh/cmd/gosh
      os: linux
      dist: xenial
      go:
        - "1.9"
        - master
      script:
        - make checkgofmt
        - make fmt_go
        - make linter
        - make test
