Title="chain33"

Loglevel="debug"
LogConsoleLevel="debug"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["114.55.101.159:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=16
verMix=16
verMax=17

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="solo"
minerstart=true

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
