
Title="chain33"
Loglevel="error"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["114.55.101.159:13802"]
enable=true
isSeed=false
dbPath="datadir/addrbook"
version=9
verMix=9
verMax=10

[mempool]
poolCacheSize=10240
minTxFee=1000000


[consensus]
name="solo"
minerstart=false
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
