
Title="chain33"
Loglevel="info"
LogConsoleLevel="info"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["54.222.210.199:13802"]
enable=true
isSeed=false
dbPath="datadir/addrbook"

version=5
verMix=5
verMax=6

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="raft"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
nodeId=1
peersURL="http://127.0.0.1:9021"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
