Title="chain33"

Loglevel="debug"
LogConsoleLevel="info"
LogFile="chain33.log"
[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=false
singleMode=false

[p2p]
seeds=["47.104.125.151:13802","47.104.125.97:13802","47.104.125.177:13802"]
enable=true
isSeed=false
serverStart=false
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=118
verMix=118
verMax=119

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]
[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
name="ticket"
minerstart=true

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
signType="secp256k1"

[exec]
