<<<<<<< HEAD
Title="chain33"

Loglevel="info"
LogConsoleLevel="info"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["54.222.210.199:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
version=5
verMix=5
verMax=6
grpcLogFile="grpc33.log"

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="raft"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
nodeId=1
raftApiPort=9121
peersURL="http://127.0.0.1:9021"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
=======
Title="chain33"

Loglevel="debug"
LogConsoleLevel="info"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["114.55.101.159:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=16
verMix=16
verMax=17

[mempool]
poolCacheSize=10240
minTxFee=1000000


[consensus]
name="solo"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
>>>>>>> origin/develop
