Title="chain33"

Loglevel="info"
LogConsoleLevel="info"
LogFile="chain33.log"
[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=false
singleMode=false

[p2p]
seeds=["192.168.3.4:13802","192.168.3.13:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=118
verMix=118
verMax=119

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]
[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
name="pbft"
minerstart=false
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
timeoutPropose=3000
timeoutProposeDelta=500
timeoutPrevote=1000
timeoutPrevoteDelta=500
timeoutPrecommit=1000
timeoutPrecommitDelta=500
timeoutCommit=1000
skipTimeoutCommit=false
createEmptyBlocks=false
createEmptyBlocksInterval=0
seeds=["192.168.3.13:46656","192.168.3.4:46656"]

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
signType="secp256k1"

[exec]
