
Title="chain33"

Loglevel="info"
LogConsoleLevel="error"
LogFile="chain33.log"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["114.55.101.158:13802"]
enable=true
isSeed=false
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=11
verMix=11
verMax=12

[mempool]
poolCacheSize=10240
minTxFee=1000000


[consensus]
name="solo"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
