
Title="chain33"
Loglevel="info"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["ec2-54-222-210-199.cn-north-1.compute.amazonaws.com.cn:13802"]
enable=true
isSeed=false
dbPath="datadir/addrbook"
version=8
verMix=7
verMax=8
[mempool]
poolCacheSize=1024
minTxFee=1000000

[consensus]
name="raft"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
nodeId=1
peersURL="http://127.0.0.1:9021"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
