
Title="chain33"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
dbPath="datadir"


[p2p]
seeds=["114.55.101.159:13802"]
isSeed=false
seedPort=13802
dbPath="datadir/addrbook"

[mempool]
poolSize=1024
minFee=1000000


[consensus]
name="solo"
genesis="14sdfswersdfsfwefwjkpojo"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
