
Title="chain33"

Loglevel="info"
LogConsoleLevel="info"
LogFile="chain33.log"
[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=true
singleMode=true

[p2p]
seeds=["127.0.0.1:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
version=15
verMix=15
verMax=16
grpcLogFile="grpc33.log"

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]
[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
name="raft"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
nodeId=1
raftApiPort=9121
isNewJoinNode=false
peersURL="http://127.0.0.1:9021"
readOnlyPeersURL=""
addPeersURL=""
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
signType="secp256k1"

[exec]
