Title="chain33"


[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 20
# 最多保存的历史日志文件个数
maxBackups = 20
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = false
# 是否打印调用源文件和行号
callerFile = true
# 是否打印调用方法
callerFunction = true

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=false
singleMode=true

[p2p]
seeds=["47.104.125.151:13802","47.104.125.97:13802","47.104.125.177:13802"]
enable=true
isSeed=true
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=216
verMix=216
verMax=217

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="solo"
minerstart=true

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
driver="leveldb"
dbPath="datadir/wallet"

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]

[exec]
minExecFee=100000
