Title="chain33"

Loglevel="info"
LogConsoleLevel="debug"
LogFile="chain33.log"

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="gobadgerdb"
dbPath="datadir"
isStrongConsistency=false
singleMode=false

[p2p]
seeds=["47.104.125.151:13802","47.104.125.97:13802","47.104.125.177:13802"]
enable=true
isSeed=false
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=118
verMix=118
verMax=119

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="ticket"
minerstart=true

[store]
driver="gobadgerdb"
dbPath="datadir/mavltree"

[localstore]
driver="gobadgerdb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
driver="gobadgerdb"
dbPath="datadir/wallet"
signType="secp256k1"
[exec]
