chain33host="http://120.79.156.149:8801"
whitelist=["127.0.0.1", "192.168.0.114", "localhost"]
jrpcBindAddr="localhost:8866"
dataDir="/var/www/html/miner_accounts/"
minerAddr=["1FB8L3DykVF7Y78bRfUrRcMZwesKue7CyR", "1Lw6QLShKVbKM6QvMaCQwTh5Uhmy4644CG", "1PSYYfCbtSeT1vJTvSKmQvhz8y6VhtddWi", "1BG9ZoKtgU5bhKLpcsrncZ6xdzFCgjrZud", "1G7s64AgX1ySDcUdSW5vDa8jTYQMnZktCd", "1FiDC6XWHLe7fDMhof8wJ3dty24f6aKKjK", "1AMvuuQ7V7FPQ4hkvHQdgNWy8wVL4d4hmp", "1ExRRLoJXa8LzXdNxnJvBkVNZpVw3QWMi4", "1KNGHukhbBnbWWnMYxu1C7YMoCj45Z3amm", "1AH9HRd4WBJ824h9PP1jYpvRZ4BSA4oN6Y"]
