
Title="chain33"
Loglevel="debug"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["113.55.101.159:13802"]
enable=true
isSeed=false
dbPath="datadir/addrbook"
version=8
verMix=7
verMax=8
[mempool]
poolCacheSize=1024
minTxFee=1000000


[consensus]
name="solo"
minerstart=true
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
