// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paracross.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// stateDB
type ParacrossStatusDetails struct {
	Addrs     []string `protobuf:"bytes,1,rep,name=addrs" json:"addrs,omitempty"`
	StateHash [][]byte `protobuf:"bytes,2,rep,name=stateHash,proto3" json:"stateHash,omitempty"`
}

func (m *ParacrossStatusDetails) Reset()                    { *m = ParacrossStatusDetails{} }
func (m *ParacrossStatusDetails) String() string            { return proto.CompactTextString(m) }
func (*ParacrossStatusDetails) ProtoMessage()               {}
func (*ParacrossStatusDetails) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

func (m *ParacrossStatusDetails) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *ParacrossStatusDetails) GetStateHash() [][]byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

type ParacrossHeightStatus struct {
	// ing, done
	Status  int32                   `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Title   string                  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Height  int64                   `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Details *ParacrossStatusDetails `protobuf:"bytes,4,opt,name=details" json:"details,omitempty"`
}

func (m *ParacrossHeightStatus) Reset()                    { *m = ParacrossHeightStatus{} }
func (m *ParacrossHeightStatus) String() string            { return proto.CompactTextString(m) }
func (*ParacrossHeightStatus) ProtoMessage()               {}
func (*ParacrossHeightStatus) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func (m *ParacrossHeightStatus) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ParacrossHeightStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossHeightStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossHeightStatus) GetDetails() *ParacrossStatusDetails {
	if m != nil {
		return m.Details
	}
	return nil
}

type ParacrossStatus struct {
	Title  string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *ParacrossStatus) Reset()                    { *m = ParacrossStatus{} }
func (m *ParacrossStatus) String() string            { return proto.CompactTextString(m) }
func (*ParacrossStatus) ProtoMessage()               {}
func (*ParacrossStatus) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{2} }

func (m *ParacrossStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// action
type ParacrossNodeStatus struct {
	Title         string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Height        int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	StateHash     []byte `protobuf:"bytes,3,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	MainStateHash []byte `protobuf:"bytes,4,opt,name=mainStateHash,proto3" json:"mainStateHash,omitempty"`
	TxCounts      uint32 `protobuf:"varint,5,opt,name=txCounts" json:"txCounts,omitempty"`
	TxResult      []byte `protobuf:"bytes,6,opt,name=txResult,proto3" json:"txResult,omitempty"`
}

func (m *ParacrossNodeStatus) Reset()                    { *m = ParacrossNodeStatus{} }
func (m *ParacrossNodeStatus) String() string            { return proto.CompactTextString(m) }
func (*ParacrossNodeStatus) ProtoMessage()               {}
func (*ParacrossNodeStatus) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{3} }

func (m *ParacrossNodeStatus) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParacrossNodeStatus) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ParacrossNodeStatus) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetMainStateHash() []byte {
	if m != nil {
		return m.MainStateHash
	}
	return nil
}

func (m *ParacrossNodeStatus) GetTxCounts() uint32 {
	if m != nil {
		return m.TxCounts
	}
	return 0
}

func (m *ParacrossNodeStatus) GetTxResult() []byte {
	if m != nil {
		return m.TxResult
	}
	return nil
}

type ParacrossCommitAction struct {
	Status *ParacrossNodeStatus `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *ParacrossCommitAction) Reset()                    { *m = ParacrossCommitAction{} }
func (m *ParacrossCommitAction) String() string            { return proto.CompactTextString(m) }
func (*ParacrossCommitAction) ProtoMessage()               {}
func (*ParacrossCommitAction) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{4} }

func (m *ParacrossCommitAction) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ParacrossAction struct {
	// Types that are valid to be assigned to Value:
	//	*ParacrossAction_Commit
	Value isParacrossAction_Value `protobuf_oneof:"value"`
	Ty    int32                   `protobuf:"varint,2,opt,name=ty" json:"ty,omitempty"`
}

func (m *ParacrossAction) Reset()                    { *m = ParacrossAction{} }
func (m *ParacrossAction) String() string            { return proto.CompactTextString(m) }
func (*ParacrossAction) ProtoMessage()               {}
func (*ParacrossAction) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{5} }

type isParacrossAction_Value interface {
	isParacrossAction_Value()
}

type ParacrossAction_Commit struct {
	Commit *ParacrossCommitAction `protobuf:"bytes,1,opt,name=commit,oneof"`
}

func (*ParacrossAction_Commit) isParacrossAction_Value() {}

func (m *ParacrossAction) GetValue() isParacrossAction_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ParacrossAction) GetCommit() *ParacrossCommitAction {
	if x, ok := m.GetValue().(*ParacrossAction_Commit); ok {
		return x.Commit
	}
	return nil
}

func (m *ParacrossAction) GetTy() int32 {
	if m != nil {
		return m.Ty
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ParacrossAction) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ParacrossAction_OneofMarshaler, _ParacrossAction_OneofUnmarshaler, _ParacrossAction_OneofSizer, []interface{}{
		(*ParacrossAction_Commit)(nil),
	}
}

func _ParacrossAction_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ParacrossAction)
	// value
	switch x := m.Value.(type) {
	case *ParacrossAction_Commit:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Commit); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ParacrossAction.Value has unexpected type %T", x)
	}
	return nil
}

func _ParacrossAction_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ParacrossAction)
	switch tag {
	case 1: // value.commit
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ParacrossCommitAction)
		err := b.DecodeMessage(msg)
		m.Value = &ParacrossAction_Commit{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ParacrossAction_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ParacrossAction)
	// value
	switch x := m.Value.(type) {
	case *ParacrossAction_Commit:
		s := proto.Size(x.Commit)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// logs
type ReceiptParacrossCommit struct {
	Addr    string                 `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Status  *ParacrossNodeStatus   `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	Prev    *ParacrossHeightStatus `protobuf:"bytes,3,opt,name=prev" json:"prev,omitempty"`
	Current *ParacrossHeightStatus `protobuf:"bytes,4,opt,name=current" json:"current,omitempty"`
}

func (m *ReceiptParacrossCommit) Reset()                    { *m = ReceiptParacrossCommit{} }
func (m *ReceiptParacrossCommit) String() string            { return proto.CompactTextString(m) }
func (*ReceiptParacrossCommit) ProtoMessage()               {}
func (*ReceiptParacrossCommit) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{6} }

func (m *ReceiptParacrossCommit) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptParacrossCommit) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReceiptParacrossCommit) GetPrev() *ParacrossHeightStatus {
	if m != nil {
		return m.Prev
	}
	return nil
}

func (m *ReceiptParacrossCommit) GetCurrent() *ParacrossHeightStatus {
	if m != nil {
		return m.Current
	}
	return nil
}

type ReceiptParacrossDone struct {
	// most-count/commit-count/total-count
	N         []int32 `protobuf:"varint,1,rep,packed,name=n" json:"n,omitempty"`
	Title     string  `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Height    int64   `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	StateHash []byte  `protobuf:"bytes,4,opt,name=stateHash,proto3" json:"stateHash,omitempty"`
	TxCounts  uint32  `protobuf:"varint,5,opt,name=txCounts" json:"txCounts,omitempty"`
	TxResult  []byte  `protobuf:"bytes,6,opt,name=txResult,proto3" json:"txResult,omitempty"`
}

func (m *ReceiptParacrossDone) Reset()                    { *m = ReceiptParacrossDone{} }
func (m *ReceiptParacrossDone) String() string            { return proto.CompactTextString(m) }
func (*ReceiptParacrossDone) ProtoMessage()               {}
func (*ReceiptParacrossDone) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{7} }

func (m *ReceiptParacrossDone) GetN() []int32 {
	if m != nil {
		return m.N
	}
	return nil
}

func (m *ReceiptParacrossDone) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReceiptParacrossDone) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ReceiptParacrossDone) GetStateHash() []byte {
	if m != nil {
		return m.StateHash
	}
	return nil
}

func (m *ReceiptParacrossDone) GetTxCounts() uint32 {
	if m != nil {
		return m.TxCounts
	}
	return 0
}

func (m *ReceiptParacrossDone) GetTxResult() []byte {
	if m != nil {
		return m.TxResult
	}
	return nil
}

type ReceiptParacrossRecord struct {
	Addr   string               `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Status *ParacrossNodeStatus `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ReceiptParacrossRecord) Reset()                    { *m = ReceiptParacrossRecord{} }
func (m *ReceiptParacrossRecord) String() string            { return proto.CompactTextString(m) }
func (*ReceiptParacrossRecord) ProtoMessage()               {}
func (*ReceiptParacrossRecord) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{8} }

func (m *ReceiptParacrossRecord) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReceiptParacrossRecord) GetStatus() *ParacrossNodeStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// LocalDB
// title-height-addr : txHash
type ParacrossTx struct {
	TxHash string `protobuf:"bytes,1,opt,name=txHash" json:"txHash,omitempty"`
}

func (m *ParacrossTx) Reset()                    { *m = ParacrossTx{} }
func (m *ParacrossTx) String() string            { return proto.CompactTextString(m) }
func (*ParacrossTx) ProtoMessage()               {}
func (*ParacrossTx) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{9} }

func (m *ParacrossTx) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

// query
type ReqParacrossTitleHeight struct {
	Title  string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
}

func (m *ReqParacrossTitleHeight) Reset()                    { *m = ReqParacrossTitleHeight{} }
func (m *ReqParacrossTitleHeight) String() string            { return proto.CompactTextString(m) }
func (*ReqParacrossTitleHeight) ProtoMessage()               {}
func (*ReqParacrossTitleHeight) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{10} }

func (m *ReqParacrossTitleHeight) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ReqParacrossTitleHeight) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type RespParacrossTitles struct {
	Titles []*ReceiptParacrossDone `protobuf:"bytes,1,rep,name=titles" json:"titles,omitempty"`
}

func (m *RespParacrossTitles) Reset()                    { *m = RespParacrossTitles{} }
func (m *RespParacrossTitles) String() string            { return proto.CompactTextString(m) }
func (*RespParacrossTitles) ProtoMessage()               {}
func (*RespParacrossTitles) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{11} }

func (m *RespParacrossTitles) GetTitles() []*ReceiptParacrossDone {
	if m != nil {
		return m.Titles
	}
	return nil
}

func init() {
	proto.RegisterType((*ParacrossStatusDetails)(nil), "types.ParacrossStatusDetails")
	proto.RegisterType((*ParacrossHeightStatus)(nil), "types.ParacrossHeightStatus")
	proto.RegisterType((*ParacrossStatus)(nil), "types.ParacrossStatus")
	proto.RegisterType((*ParacrossNodeStatus)(nil), "types.ParacrossNodeStatus")
	proto.RegisterType((*ParacrossCommitAction)(nil), "types.ParacrossCommitAction")
	proto.RegisterType((*ParacrossAction)(nil), "types.ParacrossAction")
	proto.RegisterType((*ReceiptParacrossCommit)(nil), "types.ReceiptParacrossCommit")
	proto.RegisterType((*ReceiptParacrossDone)(nil), "types.ReceiptParacrossDone")
	proto.RegisterType((*ReceiptParacrossRecord)(nil), "types.ReceiptParacrossRecord")
	proto.RegisterType((*ParacrossTx)(nil), "types.ParacrossTx")
	proto.RegisterType((*ReqParacrossTitleHeight)(nil), "types.ReqParacrossTitleHeight")
	proto.RegisterType((*RespParacrossTitles)(nil), "types.RespParacrossTitles")
}

func init() { proto.RegisterFile("paracross.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0xc5, 0x69, 0x92, 0xb2, 0xdb, 0x8d, 0x49, 0xde, 0x28, 0xd1, 0x18, 0x52, 0x64, 0x81, 0x94,
	0xa7, 0x0a, 0x75, 0xd2, 0x78, 0x44, 0xb0, 0x49, 0x54, 0x80, 0x10, 0xf2, 0xf8, 0x00, 0xbc, 0xc4,
	0xa2, 0x91, 0xda, 0x38, 0xc4, 0x37, 0x53, 0xfb, 0x23, 0x7c, 0x03, 0x7f, 0xc1, 0x3b, 0x5f, 0x85,
	0xe2, 0xb8, 0x69, 0x12, 0x2a, 0xc4, 0xa6, 0xbd, 0xf9, 0xda, 0xe7, 0x9e, 0xeb, 0x73, 0xee, 0xb5,
	0xe1, 0x30, 0x17, 0x85, 0x88, 0x0b, 0xa5, 0xf5, 0x24, 0x2f, 0x14, 0x2a, 0xea, 0xe1, 0x3a, 0x97,
	0x9a, 0x7d, 0x84, 0xf1, 0xe7, 0xcd, 0xc9, 0x15, 0x0a, 0x2c, 0xf5, 0xa5, 0x44, 0x91, 0x2e, 0x34,
	0x3d, 0x06, 0x4f, 0x24, 0x49, 0xa1, 0x03, 0x12, 0x0e, 0xa2, 0x3d, 0x5e, 0x07, 0xf4, 0x14, 0xf6,
	0x34, 0x0a, 0x94, 0x33, 0xa1, 0xe7, 0x81, 0x13, 0x0e, 0xa2, 0x7d, 0xbe, 0xdd, 0x60, 0x3f, 0x08,
	0x3c, 0x6e, 0xe8, 0x66, 0x32, 0xfd, 0x36, 0xc7, 0x9a, 0x94, 0x8e, 0xc1, 0xd7, 0x66, 0x15, 0x90,
	0x90, 0x44, 0x1e, 0xb7, 0x51, 0x55, 0x05, 0x53, 0x5c, 0xc8, 0xc0, 0x09, 0x49, 0x55, 0xc5, 0x04,
	0x15, 0x7a, 0x6e, 0xb2, 0x83, 0x41, 0x48, 0xa2, 0x01, 0xb7, 0x11, 0x7d, 0x05, 0xc3, 0xa4, 0xbe,
	0x5e, 0xe0, 0x86, 0x24, 0x1a, 0x4d, 0x9f, 0x4d, 0x8c, 0x8c, 0xc9, 0x6e, 0x0d, 0x7c, 0x83, 0x66,
	0xaf, 0xe1, 0xb0, 0x07, 0xd9, 0x56, 0x26, 0xbb, 0x2b, 0x3b, 0xed, 0xca, 0xec, 0x17, 0x81, 0xa3,
	0x86, 0xe1, 0x93, 0x4a, 0xe4, 0x5d, 0x58, 0xba, 0xee, 0x55, 0xd2, 0xda, 0xee, 0xd1, 0xe7, 0x70,
	0xb0, 0x14, 0x69, 0x76, 0xd5, 0x20, 0x5c, 0x83, 0xe8, 0x6e, 0xd2, 0x13, 0x78, 0x88, 0xab, 0x0b,
	0x55, 0x66, 0xa8, 0x03, 0x2f, 0x24, 0xd1, 0x01, 0x6f, 0xe2, 0xfa, 0x8c, 0x4b, 0x5d, 0x2e, 0x30,
	0xf0, 0x4d, 0x72, 0x13, 0xb3, 0x0f, 0xad, 0xd6, 0x5c, 0xa8, 0xe5, 0x32, 0xc5, 0x37, 0x31, 0xa6,
	0x2a, 0xa3, 0xd3, 0x4e, 0x6b, 0x46, 0xd3, 0x93, 0xbe, 0xa7, 0x5b, 0xb9, 0x9b, 0xb6, 0xb1, 0xeb,
	0x96, 0x9f, 0x96, 0xe6, 0x1c, 0xfc, 0xd8, 0xd0, 0x5a, 0x9a, 0xd3, 0x3e, 0x4d, 0xbb, 0xe8, 0xec,
	0x01, 0xb7, 0x68, 0xfa, 0x08, 0x1c, 0x5c, 0x1b, 0x9f, 0x3c, 0xee, 0xe0, 0xfa, 0xed, 0x10, 0xbc,
	0x1b, 0xb1, 0x28, 0x25, 0xfb, 0x4d, 0x60, 0xcc, 0x65, 0x2c, 0xd3, 0x1c, 0x7b, 0x1c, 0x94, 0x82,
	0x5b, 0x8d, 0xa3, 0x35, 0xdd, 0xac, 0x5b, 0x32, 0x9c, 0xff, 0x95, 0x41, 0x5f, 0x82, 0x9b, 0x17,
	0xf2, 0xc6, 0xb4, 0x62, 0xc7, 0x8d, 0xdb, 0x13, 0xcc, 0x0d, 0x92, 0x9e, 0xc3, 0x30, 0x2e, 0x8b,
	0x42, 0x66, 0x68, 0x27, 0xf0, 0xdf, 0x49, 0x1b, 0x30, 0xfb, 0x49, 0xe0, 0xb8, 0x2f, 0xe6, 0x52,
	0x65, 0x92, 0xee, 0x03, 0xc9, 0xcc, 0x13, 0xf3, 0x38, 0xc9, 0x6e, 0xf9, 0x1c, 0x3a, 0xe3, 0xe4,
	0xf6, 0xc7, 0xe9, 0xae, 0x83, 0xf2, 0xf5, 0x6f, 0xdb, 0xb9, 0x8c, 0x55, 0x91, 0xdc, 0x97, 0xed,
	0xec, 0x05, 0x8c, 0x9a, 0xe3, 0x2f, 0xab, 0x4a, 0x1e, 0xae, 0x8c, 0x86, 0x9a, 0xd8, 0x46, 0xec,
	0x1d, 0x3c, 0xe1, 0xf2, 0xfb, 0x16, 0x59, 0x79, 0x51, 0xbb, 0x7b, 0xcb, 0xc7, 0xfb, 0x1e, 0x8e,
	0xb8, 0xd4, 0x79, 0x97, 0x49, 0xd3, 0x33, 0xf0, 0x4d, 0x5e, 0xfd, 0xc5, 0x8d, 0xa6, 0x4f, 0xed,
	0xd5, 0x77, 0xf5, 0x89, 0x5b, 0xe8, 0xb5, 0x6f, 0xbe, 0xcf, 0xb3, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x5a, 0x5c, 0x7e, 0x5f, 0x51, 0x05, 0x00, 0x00,
}
