// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Grpcservice service

type GrpcserviceClient interface {
	// chain33 对外提供服务的接口
	// 区块链接口
	GetBlocks(ctx context.Context, in *ReqBlocks, opts ...grpc.CallOption) (*Reply, error)
	GetLastHeader(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Header, error)
	// 交易接口
	CreateRawTransaction(ctx context.Context, in *CreateTx, opts ...grpc.CallOption) (*UnsignTx, error)
	SendRawTransaction(ctx context.Context, in *SignedTx, opts ...grpc.CallOption) (*Reply, error)
	QueryTransaction(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*TransactionDetail, error)
	SendTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Reply, error)
	GetTransactionByAddr(ctx context.Context, in *ReqAddr, opts ...grpc.CallOption) (*ReplyTxInfos, error)
	GetTransactionByHashes(ctx context.Context, in *ReqHashes, opts ...grpc.CallOption) (*TransactionDetails, error)
	// 缓存接口
	GetMemPool(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*ReplyTxList, error)
	// 钱包接口
	GetAccounts(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*WalletAccounts, error)
	NewAccount(ctx context.Context, in *ReqNewAccount, opts ...grpc.CallOption) (*WalletAccount, error)
	WalletTransactionList(ctx context.Context, in *ReqWalletTransactionList, opts ...grpc.CallOption) (*WalletTxDetails, error)
	ImportPrivKey(ctx context.Context, in *ReqWalletImportPrivKey, opts ...grpc.CallOption) (*WalletAccount, error)
	SendToAddress(ctx context.Context, in *ReqWalletSendToAddress, opts ...grpc.CallOption) (*ReplyHash, error)
	SetTxFee(ctx context.Context, in *ReqWalletSetFee, opts ...grpc.CallOption) (*Reply, error)
	SetLabl(ctx context.Context, in *ReqWalletSetLabel, opts ...grpc.CallOption) (*WalletAccount, error)
	MergeBalance(ctx context.Context, in *ReqWalletMergeBalance, opts ...grpc.CallOption) (*ReplyHashes, error)
	SetPasswd(ctx context.Context, in *ReqWalletSetPasswd, opts ...grpc.CallOption) (*Reply, error)
	Lock(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Reply, error)
	UnLock(ctx context.Context, in *WalletUnLock, opts ...grpc.CallOption) (*Reply, error)
	GetPeerInfo(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*PeerList, error)
	GetLastMemPool(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*ReplyTxList, error)
	GetWalletStatus(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*WalletStatus, error)
	// 区块浏览器接口
	GetBlockOverview(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*BlockOverview, error)
	GetAddrOverview(ctx context.Context, in *ReqAddr, opts ...grpc.CallOption) (*AddrOverview, error)
	GetBlockHash(ctx context.Context, in *ReqInt, opts ...grpc.CallOption) (*ReplyHash, error)
	// seed
	GenSeed(ctx context.Context, in *GenSeedLang, opts ...grpc.CallOption) (*ReplySeed, error)
	GetSeed(ctx context.Context, in *GetSeedByPw, opts ...grpc.CallOption) (*ReplySeed, error)
	SaveSeed(ctx context.Context, in *SaveSeedByPw, opts ...grpc.CallOption) (*Reply, error)
	// Balance Query
	GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*Accounts, error)
	QueryChain(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Reply, error)
	// Miner
	SetAutoMining(ctx context.Context, in *MinerFlag, opts ...grpc.CallOption) (*Reply, error)
	//
	GetHexTxByHash(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*HexTx, error)
	GetTicketCount(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Int64, error)
	DumpPrivkey(ctx context.Context, in *ReqStr, opts ...grpc.CallOption) (*ReplyStr, error)
}

type grpcserviceClient struct {
	cc *grpc.ClientConn
}

func NewGrpcserviceClient(cc *grpc.ClientConn) GrpcserviceClient {
	return &grpcserviceClient{cc}
}

func (c *grpcserviceClient) GetBlocks(ctx context.Context, in *ReqBlocks, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetBlocks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetLastHeader(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Header, error) {
	out := new(Header)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetLastHeader", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) CreateRawTransaction(ctx context.Context, in *CreateTx, opts ...grpc.CallOption) (*UnsignTx, error) {
	out := new(UnsignTx)
	err := grpc.Invoke(ctx, "/types.grpcservice/CreateRawTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SendRawTransaction(ctx context.Context, in *SignedTx, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SendRawTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) QueryTransaction(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*TransactionDetail, error) {
	out := new(TransactionDetail)
	err := grpc.Invoke(ctx, "/types.grpcservice/QueryTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SendTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SendTransaction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetTransactionByAddr(ctx context.Context, in *ReqAddr, opts ...grpc.CallOption) (*ReplyTxInfos, error) {
	out := new(ReplyTxInfos)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetTransactionByAddr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetTransactionByHashes(ctx context.Context, in *ReqHashes, opts ...grpc.CallOption) (*TransactionDetails, error) {
	out := new(TransactionDetails)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetTransactionByHashes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetMemPool(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*ReplyTxList, error) {
	out := new(ReplyTxList)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetMemPool", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetAccounts(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*WalletAccounts, error) {
	out := new(WalletAccounts)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetAccounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) NewAccount(ctx context.Context, in *ReqNewAccount, opts ...grpc.CallOption) (*WalletAccount, error) {
	out := new(WalletAccount)
	err := grpc.Invoke(ctx, "/types.grpcservice/NewAccount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) WalletTransactionList(ctx context.Context, in *ReqWalletTransactionList, opts ...grpc.CallOption) (*WalletTxDetails, error) {
	out := new(WalletTxDetails)
	err := grpc.Invoke(ctx, "/types.grpcservice/WalletTransactionList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) ImportPrivKey(ctx context.Context, in *ReqWalletImportPrivKey, opts ...grpc.CallOption) (*WalletAccount, error) {
	out := new(WalletAccount)
	err := grpc.Invoke(ctx, "/types.grpcservice/ImportPrivKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SendToAddress(ctx context.Context, in *ReqWalletSendToAddress, opts ...grpc.CallOption) (*ReplyHash, error) {
	out := new(ReplyHash)
	err := grpc.Invoke(ctx, "/types.grpcservice/SendToAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SetTxFee(ctx context.Context, in *ReqWalletSetFee, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SetTxFee", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SetLabl(ctx context.Context, in *ReqWalletSetLabel, opts ...grpc.CallOption) (*WalletAccount, error) {
	out := new(WalletAccount)
	err := grpc.Invoke(ctx, "/types.grpcservice/SetLabl", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) MergeBalance(ctx context.Context, in *ReqWalletMergeBalance, opts ...grpc.CallOption) (*ReplyHashes, error) {
	out := new(ReplyHashes)
	err := grpc.Invoke(ctx, "/types.grpcservice/MergeBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SetPasswd(ctx context.Context, in *ReqWalletSetPasswd, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SetPasswd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) Lock(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/Lock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) UnLock(ctx context.Context, in *WalletUnLock, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/UnLock", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetPeerInfo(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*PeerList, error) {
	out := new(PeerList)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetPeerInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetLastMemPool(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*ReplyTxList, error) {
	out := new(ReplyTxList)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetLastMemPool", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetWalletStatus(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*WalletStatus, error) {
	out := new(WalletStatus)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetWalletStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetBlockOverview(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*BlockOverview, error) {
	out := new(BlockOverview)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetBlockOverview", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetAddrOverview(ctx context.Context, in *ReqAddr, opts ...grpc.CallOption) (*AddrOverview, error) {
	out := new(AddrOverview)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetAddrOverview", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetBlockHash(ctx context.Context, in *ReqInt, opts ...grpc.CallOption) (*ReplyHash, error) {
	out := new(ReplyHash)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetBlockHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GenSeed(ctx context.Context, in *GenSeedLang, opts ...grpc.CallOption) (*ReplySeed, error) {
	out := new(ReplySeed)
	err := grpc.Invoke(ctx, "/types.grpcservice/GenSeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetSeed(ctx context.Context, in *GetSeedByPw, opts ...grpc.CallOption) (*ReplySeed, error) {
	out := new(ReplySeed)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetSeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SaveSeed(ctx context.Context, in *SaveSeedByPw, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SaveSeed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*Accounts, error) {
	out := new(Accounts)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetBalance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) QueryChain(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/QueryChain", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) SetAutoMining(ctx context.Context, in *MinerFlag, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := grpc.Invoke(ctx, "/types.grpcservice/SetAutoMining", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetHexTxByHash(ctx context.Context, in *ReqHash, opts ...grpc.CallOption) (*HexTx, error) {
	out := new(HexTx)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetHexTxByHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) GetTicketCount(ctx context.Context, in *ReqNil, opts ...grpc.CallOption) (*Int64, error) {
	out := new(Int64)
	err := grpc.Invoke(ctx, "/types.grpcservice/GetTicketCount", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcserviceClient) DumpPrivkey(ctx context.Context, in *ReqStr, opts ...grpc.CallOption) (*ReplyStr, error) {
	out := new(ReplyStr)
	err := grpc.Invoke(ctx, "/types.grpcservice/DumpPrivkey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Grpcservice service

type GrpcserviceServer interface {
	// chain33 对外提供服务的接口
	// 区块链接口
	GetBlocks(context.Context, *ReqBlocks) (*Reply, error)
	GetLastHeader(context.Context, *ReqNil) (*Header, error)
	// 交易接口
	CreateRawTransaction(context.Context, *CreateTx) (*UnsignTx, error)
	SendRawTransaction(context.Context, *SignedTx) (*Reply, error)
	QueryTransaction(context.Context, *ReqHash) (*TransactionDetail, error)
	SendTransaction(context.Context, *Transaction) (*Reply, error)
	GetTransactionByAddr(context.Context, *ReqAddr) (*ReplyTxInfos, error)
	GetTransactionByHashes(context.Context, *ReqHashes) (*TransactionDetails, error)
	// 缓存接口
	GetMemPool(context.Context, *ReqNil) (*ReplyTxList, error)
	// 钱包接口
	GetAccounts(context.Context, *ReqNil) (*WalletAccounts, error)
	NewAccount(context.Context, *ReqNewAccount) (*WalletAccount, error)
	WalletTransactionList(context.Context, *ReqWalletTransactionList) (*WalletTxDetails, error)
	ImportPrivKey(context.Context, *ReqWalletImportPrivKey) (*WalletAccount, error)
	SendToAddress(context.Context, *ReqWalletSendToAddress) (*ReplyHash, error)
	SetTxFee(context.Context, *ReqWalletSetFee) (*Reply, error)
	SetLabl(context.Context, *ReqWalletSetLabel) (*WalletAccount, error)
	MergeBalance(context.Context, *ReqWalletMergeBalance) (*ReplyHashes, error)
	SetPasswd(context.Context, *ReqWalletSetPasswd) (*Reply, error)
	Lock(context.Context, *ReqNil) (*Reply, error)
	UnLock(context.Context, *WalletUnLock) (*Reply, error)
	GetPeerInfo(context.Context, *ReqNil) (*PeerList, error)
	GetLastMemPool(context.Context, *ReqNil) (*ReplyTxList, error)
	GetWalletStatus(context.Context, *ReqNil) (*WalletStatus, error)
	// 区块浏览器接口
	GetBlockOverview(context.Context, *ReqHash) (*BlockOverview, error)
	GetAddrOverview(context.Context, *ReqAddr) (*AddrOverview, error)
	GetBlockHash(context.Context, *ReqInt) (*ReplyHash, error)
	// seed
	GenSeed(context.Context, *GenSeedLang) (*ReplySeed, error)
	GetSeed(context.Context, *GetSeedByPw) (*ReplySeed, error)
	SaveSeed(context.Context, *SaveSeedByPw) (*Reply, error)
	// Balance Query
	GetBalance(context.Context, *ReqBalance) (*Accounts, error)
	QueryChain(context.Context, *Query) (*Reply, error)
	// Miner
	SetAutoMining(context.Context, *MinerFlag) (*Reply, error)
	//
	GetHexTxByHash(context.Context, *ReqHash) (*HexTx, error)
	GetTicketCount(context.Context, *ReqNil) (*Int64, error)
	DumpPrivkey(context.Context, *ReqStr) (*ReplyStr, error)
}

func RegisterGrpcserviceServer(s *grpc.Server, srv GrpcserviceServer) {
	s.RegisterService(&_Grpcservice_serviceDesc, srv)
}

func _Grpcservice_GetBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlocks)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetBlocks(ctx, req.(*ReqBlocks))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetLastHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetLastHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetLastHeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetLastHeader(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_CreateRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).CreateRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/CreateRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).CreateRawTransaction(ctx, req.(*CreateTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SendRawTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignedTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SendRawTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SendRawTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SendRawTransaction(ctx, req.(*SignedTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_QueryTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).QueryTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/QueryTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).QueryTransaction(ctx, req.(*ReqHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SendTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetTransactionByAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetTransactionByAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetTransactionByAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetTransactionByAddr(ctx, req.(*ReqAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetTransactionByHashes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHashes)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetTransactionByHashes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetTransactionByHashes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetTransactionByHashes(ctx, req.(*ReqHashes))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetMemPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetMemPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetMemPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetMemPool(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetAccounts(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNewAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).NewAccount(ctx, req.(*ReqNewAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_WalletTransactionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletTransactionList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).WalletTransactionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/WalletTransactionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).WalletTransactionList(ctx, req.(*ReqWalletTransactionList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_ImportPrivKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletImportPrivKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).ImportPrivKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/ImportPrivKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).ImportPrivKey(ctx, req.(*ReqWalletImportPrivKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SendToAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletSendToAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SendToAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SendToAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SendToAddress(ctx, req.(*ReqWalletSendToAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SetTxFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletSetFee)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SetTxFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SetTxFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SetTxFee(ctx, req.(*ReqWalletSetFee))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SetLabl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletSetLabel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SetLabl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SetLabl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SetLabl(ctx, req.(*ReqWalletSetLabel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_MergeBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletMergeBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).MergeBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/MergeBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).MergeBalance(ctx, req.(*ReqWalletMergeBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SetPasswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqWalletSetPasswd)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SetPasswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SetPasswd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SetPasswd(ctx, req.(*ReqWalletSetPasswd))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_Lock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).Lock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/Lock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).Lock(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_UnLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletUnLock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).UnLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/UnLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).UnLock(ctx, req.(*WalletUnLock))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetPeerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetPeerInfo(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetLastMemPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetLastMemPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetLastMemPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetLastMemPool(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetWalletStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetWalletStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetWalletStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetWalletStatus(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetBlockOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetBlockOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetBlockOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetBlockOverview(ctx, req.(*ReqHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetAddrOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetAddrOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetAddrOverview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetAddrOverview(ctx, req.(*ReqAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetBlockHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqInt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetBlockHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetBlockHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetBlockHash(ctx, req.(*ReqInt))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GenSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenSeedLang)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GenSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GenSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GenSeed(ctx, req.(*GenSeedLang))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeedByPw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetSeed(ctx, req.(*GetSeedByPw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SaveSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSeedByPw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SaveSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SaveSeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SaveSeed(ctx, req.(*SaveSeedByPw))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetBalance(ctx, req.(*ReqBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_QueryChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).QueryChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/QueryChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).QueryChain(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_SetAutoMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerFlag)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).SetAutoMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/SetAutoMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).SetAutoMining(ctx, req.(*MinerFlag))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetHexTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetHexTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetHexTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetHexTxByHash(ctx, req.(*ReqHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_GetTicketCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).GetTicketCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/GetTicketCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).GetTicketCount(ctx, req.(*ReqNil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Grpcservice_DumpPrivkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqStr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcserviceServer).DumpPrivkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/types.grpcservice/DumpPrivkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcserviceServer).DumpPrivkey(ctx, req.(*ReqStr))
	}
	return interceptor(ctx, in, info, handler)
}

var _Grpcservice_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.grpcservice",
	HandlerType: (*GrpcserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlocks",
			Handler:    _Grpcservice_GetBlocks_Handler,
		},
		{
			MethodName: "GetLastHeader",
			Handler:    _Grpcservice_GetLastHeader_Handler,
		},
		{
			MethodName: "CreateRawTransaction",
			Handler:    _Grpcservice_CreateRawTransaction_Handler,
		},
		{
			MethodName: "SendRawTransaction",
			Handler:    _Grpcservice_SendRawTransaction_Handler,
		},
		{
			MethodName: "QueryTransaction",
			Handler:    _Grpcservice_QueryTransaction_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Grpcservice_SendTransaction_Handler,
		},
		{
			MethodName: "GetTransactionByAddr",
			Handler:    _Grpcservice_GetTransactionByAddr_Handler,
		},
		{
			MethodName: "GetTransactionByHashes",
			Handler:    _Grpcservice_GetTransactionByHashes_Handler,
		},
		{
			MethodName: "GetMemPool",
			Handler:    _Grpcservice_GetMemPool_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _Grpcservice_GetAccounts_Handler,
		},
		{
			MethodName: "NewAccount",
			Handler:    _Grpcservice_NewAccount_Handler,
		},
		{
			MethodName: "WalletTransactionList",
			Handler:    _Grpcservice_WalletTransactionList_Handler,
		},
		{
			MethodName: "ImportPrivKey",
			Handler:    _Grpcservice_ImportPrivKey_Handler,
		},
		{
			MethodName: "SendToAddress",
			Handler:    _Grpcservice_SendToAddress_Handler,
		},
		{
			MethodName: "SetTxFee",
			Handler:    _Grpcservice_SetTxFee_Handler,
		},
		{
			MethodName: "SetLabl",
			Handler:    _Grpcservice_SetLabl_Handler,
		},
		{
			MethodName: "MergeBalance",
			Handler:    _Grpcservice_MergeBalance_Handler,
		},
		{
			MethodName: "SetPasswd",
			Handler:    _Grpcservice_SetPasswd_Handler,
		},
		{
			MethodName: "Lock",
			Handler:    _Grpcservice_Lock_Handler,
		},
		{
			MethodName: "UnLock",
			Handler:    _Grpcservice_UnLock_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _Grpcservice_GetPeerInfo_Handler,
		},
		{
			MethodName: "GetLastMemPool",
			Handler:    _Grpcservice_GetLastMemPool_Handler,
		},
		{
			MethodName: "GetWalletStatus",
			Handler:    _Grpcservice_GetWalletStatus_Handler,
		},
		{
			MethodName: "GetBlockOverview",
			Handler:    _Grpcservice_GetBlockOverview_Handler,
		},
		{
			MethodName: "GetAddrOverview",
			Handler:    _Grpcservice_GetAddrOverview_Handler,
		},
		{
			MethodName: "GetBlockHash",
			Handler:    _Grpcservice_GetBlockHash_Handler,
		},
		{
			MethodName: "GenSeed",
			Handler:    _Grpcservice_GenSeed_Handler,
		},
		{
			MethodName: "GetSeed",
			Handler:    _Grpcservice_GetSeed_Handler,
		},
		{
			MethodName: "SaveSeed",
			Handler:    _Grpcservice_SaveSeed_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Grpcservice_GetBalance_Handler,
		},
		{
			MethodName: "QueryChain",
			Handler:    _Grpcservice_QueryChain_Handler,
		},
		{
			MethodName: "SetAutoMining",
			Handler:    _Grpcservice_SetAutoMining_Handler,
		},
		{
			MethodName: "GetHexTxByHash",
			Handler:    _Grpcservice_GetHexTxByHash_Handler,
		},
		{
			MethodName: "GetTicketCount",
			Handler:    _Grpcservice_GetTicketCount_Handler,
		},
		{
			MethodName: "DumpPrivkey",
			Handler:    _Grpcservice_DumpPrivkey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 785 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5b, 0x4f, 0xdb, 0x48,
	0x14, 0xf6, 0xc3, 0x2e, 0x90, 0x21, 0x21, 0x61, 0x08, 0x08, 0xac, 0x5d, 0xad, 0x64, 0x69, 0x5f,
	0x2a, 0x01, 0x25, 0x6d, 0x69, 0xd5, 0xaa, 0x95, 0x08, 0x28, 0x26, 0x6a, 0x42, 0x53, 0x6c, 0xd4,
	0xe7, 0x89, 0x73, 0x1a, 0xac, 0x38, 0x63, 0x77, 0x3c, 0x49, 0x9c, 0x7f, 0xd5, 0x9f, 0x58, 0xcd,
	0xf8, 0x92, 0xf1, 0x25, 0x95, 0xfa, 0xe6, 0x73, 0xf9, 0xce, 0x39, 0xe3, 0xf3, 0xcd, 0x37, 0xa8,
	0xc6, 0x02, 0xe7, 0x22, 0x60, 0x3e, 0xf7, 0xf1, 0xdf, 0x7c, 0x1d, 0x40, 0xa8, 0xd7, 0x1d, 0x7f,
	0x3e, 0xf7, 0x69, 0xec, 0xd4, 0x0f, 0x39, 0x23, 0x34, 0x24, 0x0e, 0x77, 0x33, 0x57, 0x6b, 0xec,
	0xf9, 0xce, 0xcc, 0x79, 0x26, 0x6e, 0xea, 0xa9, 0xaf, 0x88, 0xe7, 0x01, 0x4f, 0xac, 0x5a, 0xd0,
	0x09, 0x92, 0xcf, 0x06, 0x71, 0x1c, 0x7f, 0x41, 0xd3, 0xc8, 0x01, 0x44, 0xe0, 0x2c, 0xb8, 0xcf,
	0x62, 0xbb, 0xf3, 0xb3, 0x89, 0xf6, 0xa7, 0x2c, 0x70, 0x42, 0x60, 0x4b, 0xd7, 0x01, 0x7c, 0x8e,
	0x6a, 0x26, 0xf0, 0xae, 0x28, 0x1f, 0xe2, 0xd6, 0x85, 0x9c, 0xe7, 0xe2, 0x11, 0x7e, 0xc4, 0x1e,
	0xbd, 0x9e, 0x79, 0x02, 0x6f, 0x6d, 0x68, 0xf8, 0x12, 0x35, 0x4c, 0xe0, 0x03, 0x12, 0xf2, 0x7b,
	0x20, 0x13, 0x60, 0xb8, 0xb1, 0x81, 0x3c, 0xb8, 0x9e, 0x9e, 0x9a, 0x71, 0xd4, 0xd0, 0xf0, 0x7b,
	0xd4, 0xbe, 0x65, 0x40, 0x38, 0x3c, 0x92, 0x95, 0xbd, 0x39, 0x17, 0x6e, 0x26, 0x89, 0x71, 0xd0,
	0x8e, 0xf4, 0xd4, 0xf1, 0x44, 0x43, 0x77, 0x4a, 0xed, 0xc8, 0xd0, 0xf0, 0x1b, 0x84, 0x2d, 0xa0,
	0x93, 0x2d, 0x48, 0xcb, 0x9d, 0x52, 0x98, 0xd8, 0x51, 0x69, 0xc6, 0x4f, 0xa8, 0xf5, 0x75, 0x01,
	0x6c, 0xad, 0x82, 0x0e, 0x36, 0x63, 0xde, 0x93, 0xf0, 0x59, 0x3f, 0x4d, 0x6c, 0x25, 0xe7, 0x0e,
	0x38, 0x71, 0x3d, 0xd9, 0xb6, 0x29, 0xda, 0xaa, 0x70, 0x5c, 0x4e, 0x2f, 0xb5, 0xfd, 0x88, 0xda,
	0x26, 0x70, 0x25, 0xa3, 0xbb, 0xbe, 0x99, 0x4c, 0x98, 0xda, 0x5a, 0xd8, 0xfa, 0x91, 0x8a, 0xb3,
	0xa3, 0x3e, 0xfd, 0xee, 0x87, 0x86, 0x86, 0x4d, 0x74, 0x52, 0x84, 0x8b, 0x49, 0x21, 0xb7, 0x95,
	0xd8, 0xa3, 0x9f, 0x6d, 0x9b, 0x5e, 0x14, 0xba, 0x42, 0xc8, 0x04, 0x3e, 0x84, 0xf9, 0xc8, 0xf7,
	0xbd, 0xe2, 0x7e, 0x70, 0xbe, 0xf9, 0xc0, 0x0d, 0xb9, 0x3c, 0xf1, 0xbe, 0x09, 0xfc, 0x26, 0x26,
	0x4e, 0x58, 0xc4, 0x1c, 0x27, 0xe6, 0x37, 0xc9, 0xb8, 0x34, 0x4b, 0xee, 0x16, 0x3d, 0xc0, 0x2a,
	0x71, 0xe0, 0xb6, 0x82, 0xca, 0xbc, 0x7a, 0xbb, 0x0a, 0x6c, 0x68, 0xf8, 0x11, 0x1d, 0xc7, 0x2e,
	0xe5, 0x0c, 0x62, 0x1a, 0xfc, 0xdf, 0xa6, 0x4c, 0x65, 0x82, 0x7e, 0x92, 0xab, 0x68, 0x47, 0x9b,
	0x93, 0xf7, 0x50, 0xa3, 0x3f, 0x0f, 0x7c, 0xc6, 0x47, 0xcc, 0x5d, 0x7e, 0x86, 0x35, 0xfe, 0xb7,
	0x58, 0x2b, 0x17, 0xde, 0x3a, 0x5b, 0x17, 0x35, 0x24, 0x01, 0x7c, 0xb1, 0x2f, 0x08, 0xc3, 0x72,
	0x9d, 0x5c, 0x58, 0x6f, 0xa9, 0x3f, 0x55, 0xac, 0xc8, 0xd0, 0x70, 0x07, 0xed, 0x59, 0x62, 0xba,
	0x1e, 0x00, 0x3e, 0x29, 0xc3, 0x79, 0x0f, 0xa0, 0xc4, 0xa0, 0x0f, 0x68, 0xd7, 0x12, 0x97, 0x6b,
	0xec, 0xe1, 0xd3, 0x0a, 0xc8, 0x80, 0x8c, 0xc1, 0xfb, 0xcd, 0xd0, 0xf5, 0x21, 0xb0, 0x29, 0x74,
	0x89, 0x47, 0xa8, 0x03, 0xf8, 0x9f, 0x62, 0x05, 0x35, 0x9a, 0xe7, 0x41, 0xcc, 0x2a, 0x43, 0xc3,
	0xd7, 0xa8, 0x66, 0x01, 0x1f, 0x91, 0x30, 0x5c, 0x4d, 0xf0, 0x59, 0xc5, 0x08, 0x71, 0xa8, 0x34,
	0xf8, 0xff, 0xe8, 0xaf, 0x81, 0xef, 0xcc, 0x8a, 0xc4, 0x29, 0xa6, 0x9d, 0xa3, 0x9d, 0x27, 0x2a,
	0x13, 0x8f, 0x72, 0x87, 0x88, 0x9d, 0x15, 0x5a, 0x23, 0x58, 0x39, 0x02, 0x60, 0xe2, 0x8e, 0x14,
	0x8b, 0xa7, 0x32, 0x20, 0xe2, 0x19, 0x8d, 0x0f, 0x12, 0x71, 0xfa, 0x23, 0xf6, 0xbf, 0x45, 0x4d,
	0x13, 0x78, 0x72, 0x46, 0x4e, 0xf8, 0xa2, 0x74, 0x03, 0xf2, 0xe3, 0xc6, 0x39, 0x92, 0xff, 0xad,
	0x54, 0x3b, 0xbf, 0x2c, 0x85, 0x9e, 0xc2, 0xaa, 0x24, 0x34, 0xe9, 0xba, 0x72, 0x59, 0x86, 0x86,
	0xdf, 0xc9, 0xa6, 0x82, 0x41, 0x55, 0xd0, 0x9c, 0x50, 0xa8, 0x49, 0xf2, 0x7e, 0xd7, 0xd3, 0xae,
	0xa2, 0x83, 0x3a, 0x6b, 0x9f, 0xf2, 0x4a, 0x32, 0x5e, 0xa1, 0x5d, 0x13, 0xa8, 0x05, 0x30, 0xc9,
	0x94, 0x2c, 0xb1, 0x07, 0x84, 0x4e, 0xf3, 0x10, 0xe1, 0x4d, 0x21, 0xbc, 0x00, 0x91, 0x76, 0x77,
	0x3d, 0x5a, 0x55, 0x42, 0x2e, 0xd1, 0x9e, 0x45, 0x96, 0x20, 0x31, 0xe9, 0xec, 0xa9, 0x43, 0x82,
	0x8a, 0x0b, 0xee, 0x48, 0xa5, 0x4a, 0x09, 0x7b, 0xa8, 0x3c, 0x3e, 0x09, 0x4b, 0xd3, 0x1d, 0x2b,
	0x9a, 0xf3, 0x02, 0x21, 0x29, 0xee, 0xb7, 0xe2, 0x2d, 0xc4, 0x69, 0x45, 0xe9, 0x2a, 0xd5, 0xbf,
	0x12, 0xf7, 0x98, 0xdf, 0x2c, 0xb8, 0x3f, 0x74, 0xa9, 0x4b, 0xa7, 0x99, 0x92, 0x0e, 0x5d, 0x0a,
	0xac, 0xe7, 0x91, 0x69, 0x09, 0xf2, 0x52, 0x52, 0xe8, 0x1e, 0x22, 0x3b, 0x8a, 0xf5, 0xb7, 0xb4,
	0xd0, 0x7a, 0xf6, 0xc2, 0x45, 0xf2, 0x91, 0xba, 0x94, 0x08, 0xdb, 0x75, 0x66, 0xc0, 0x6f, 0xa5,
	0x10, 0x6e, 0xb9, 0x05, 0x7d, 0xca, 0xaf, 0x5f, 0xc7, 0xb4, 0xbe, 0x5b, 0xcc, 0x03, 0x21, 0x42,
	0x33, 0x58, 0xab, 0xd9, 0x16, 0x67, 0xd9, 0x91, 0xe3, 0x1f, 0xcb, 0x99, 0xa1, 0x8d, 0x77, 0xe4,
	0xcb, 0xfd, 0xea, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x61, 0x51, 0x32, 0x67, 0x38, 0x08, 0x00,
	0x00,
}
