// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wallet.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 钱包模块存贮的tx交易详细信息
// 	 tx : tx交易信息
// 	 receipt :交易收据信息
// 	 height :交易所在的区块高度
// 	 index :交易所在区块中的索引
// 	 blocktime :交易所在区块的时标
// 	 amount :交易量
// 	 fromaddr :交易打出地址
// 	 txhash : 交易对应的哈希值
// 	 actionName  :交易对应的函数调用
//   spendrecv 交易对应的输入UTXO
type WalletTxDetail struct {
	Tx           *Transaction `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	Receipt      *ReceiptData `protobuf:"bytes,2,opt,name=receipt" json:"receipt,omitempty"`
	Height       int64        `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Index        int64        `protobuf:"varint,4,opt,name=index" json:"index,omitempty"`
	Blocktime    int64        `protobuf:"varint,5,opt,name=blocktime" json:"blocktime,omitempty"`
	Amount       int64        `protobuf:"varint,6,opt,name=amount" json:"amount,omitempty"`
	SenderRecver string       `protobuf:"bytes,7,opt,name=senderRecver" json:"senderRecver,omitempty"`
	Txhash       []byte       `protobuf:"bytes,8,opt,name=txhash,proto3" json:"txhash,omitempty"`
	ActionName   string       `protobuf:"bytes,9,opt,name=actionName" json:"actionName,omitempty"`
	Spendrecv    []*UTXO      `protobuf:"bytes,10,rep,name=spendrecv" json:"spendrecv,omitempty"`
}

func (m *WalletTxDetail) Reset()                    { *m = WalletTxDetail{} }
func (m *WalletTxDetail) String() string            { return proto.CompactTextString(m) }
func (*WalletTxDetail) ProtoMessage()               {}
func (*WalletTxDetail) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{0} }

func (m *WalletTxDetail) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *WalletTxDetail) GetReceipt() *ReceiptData {
	if m != nil {
		return m.Receipt
	}
	return nil
}

func (m *WalletTxDetail) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *WalletTxDetail) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *WalletTxDetail) GetBlocktime() int64 {
	if m != nil {
		return m.Blocktime
	}
	return 0
}

func (m *WalletTxDetail) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *WalletTxDetail) GetSenderRecver() string {
	if m != nil {
		return m.SenderRecver
	}
	return ""
}

func (m *WalletTxDetail) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *WalletTxDetail) GetActionName() string {
	if m != nil {
		return m.ActionName
	}
	return ""
}

func (m *WalletTxDetail) GetSpendrecv() []*UTXO {
	if m != nil {
		return m.Spendrecv
	}
	return nil
}

type WalletTxDetails struct {
	TxDetails []*WalletTxDetail `protobuf:"bytes,1,rep,name=txDetails" json:"txDetails,omitempty"`
}

func (m *WalletTxDetails) Reset()                    { *m = WalletTxDetails{} }
func (m *WalletTxDetails) String() string            { return proto.CompactTextString(m) }
func (*WalletTxDetails) ProtoMessage()               {}
func (*WalletTxDetails) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{1} }

func (m *WalletTxDetails) GetTxDetails() []*WalletTxDetail {
	if m != nil {
		return m.TxDetails
	}
	return nil
}

// 钱包模块存贮的账户信息
// 	 privkey : 账户地址对应的私钥
// 	 label :账户地址对应的标签
// 	 addr :账户地址
// 	 timeStamp :创建账户时的时标
type WalletAccountStore struct {
	Privkey   string `protobuf:"bytes,1,opt,name=privkey" json:"privkey,omitempty"`
	Label     string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Addr      string `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
	TimeStamp string `protobuf:"bytes,4,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (m *WalletAccountStore) Reset()                    { *m = WalletAccountStore{} }
func (m *WalletAccountStore) String() string            { return proto.CompactTextString(m) }
func (*WalletAccountStore) ProtoMessage()               {}
func (*WalletAccountStore) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{2} }

func (m *WalletAccountStore) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

func (m *WalletAccountStore) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *WalletAccountStore) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *WalletAccountStore) GetTimeStamp() string {
	if m != nil {
		return m.TimeStamp
	}
	return ""
}

type WalletAccountPrivacy struct {
	ViewPubkey   []byte `protobuf:"bytes,1,opt,name=viewPubkey,proto3" json:"viewPubkey,omitempty"`
	ViewPrivKey  []byte `protobuf:"bytes,2,opt,name=viewPrivKey,proto3" json:"viewPrivKey,omitempty"`
	SpendPubkey  []byte `protobuf:"bytes,3,opt,name=spendPubkey,proto3" json:"spendPubkey,omitempty"`
	SpendPrivKey []byte `protobuf:"bytes,4,opt,name=spendPrivKey,proto3" json:"spendPrivKey,omitempty"`
}

func (m *WalletAccountPrivacy) Reset()                    { *m = WalletAccountPrivacy{} }
func (m *WalletAccountPrivacy) String() string            { return proto.CompactTextString(m) }
func (*WalletAccountPrivacy) ProtoMessage()               {}
func (*WalletAccountPrivacy) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{3} }

func (m *WalletAccountPrivacy) GetViewPubkey() []byte {
	if m != nil {
		return m.ViewPubkey
	}
	return nil
}

func (m *WalletAccountPrivacy) GetViewPrivKey() []byte {
	if m != nil {
		return m.ViewPrivKey
	}
	return nil
}

func (m *WalletAccountPrivacy) GetSpendPubkey() []byte {
	if m != nil {
		return m.SpendPubkey
	}
	return nil
}

func (m *WalletAccountPrivacy) GetSpendPrivKey() []byte {
	if m != nil {
		return m.SpendPrivKey
	}
	return nil
}

// 钱包模块通过一个随机值对钱包密码加密
// 	 pwHash : 对钱包密码和一个随机值组合进行哈希计算
// 	 randstr :对钱包密码加密的一个随机值
type WalletPwHash struct {
	PwHash  []byte `protobuf:"bytes,1,opt,name=pwHash,proto3" json:"pwHash,omitempty"`
	Randstr string `protobuf:"bytes,2,opt,name=randstr" json:"randstr,omitempty"`
}

func (m *WalletPwHash) Reset()                    { *m = WalletPwHash{} }
func (m *WalletPwHash) String() string            { return proto.CompactTextString(m) }
func (*WalletPwHash) ProtoMessage()               {}
func (*WalletPwHash) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{4} }

func (m *WalletPwHash) GetPwHash() []byte {
	if m != nil {
		return m.PwHash
	}
	return nil
}

func (m *WalletPwHash) GetRandstr() string {
	if m != nil {
		return m.Randstr
	}
	return ""
}

// 钱包当前的状态
// 	 isWalletLock : 钱包是否锁状态，true锁定，false解锁
// 	 isAutoMining :钱包是否开启挖矿功能，true开启挖矿，false关闭挖矿
// 	 isHasSeed : 钱包是否有种子，true已有，false没有
// 	 isTicketLock :钱包挖矿买票锁状态，true锁定，false解锁，只能用于挖矿转账
type WalletStatus struct {
	IsWalletLock bool `protobuf:"varint,1,opt,name=isWalletLock" json:"isWalletLock,omitempty"`
	IsAutoMining bool `protobuf:"varint,2,opt,name=isAutoMining" json:"isAutoMining,omitempty"`
	IsHasSeed    bool `protobuf:"varint,3,opt,name=isHasSeed" json:"isHasSeed,omitempty"`
	IsTicketLock bool `protobuf:"varint,4,opt,name=isTicketLock" json:"isTicketLock,omitempty"`
}

func (m *WalletStatus) Reset()                    { *m = WalletStatus{} }
func (m *WalletStatus) String() string            { return proto.CompactTextString(m) }
func (*WalletStatus) ProtoMessage()               {}
func (*WalletStatus) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{5} }

func (m *WalletStatus) GetIsWalletLock() bool {
	if m != nil {
		return m.IsWalletLock
	}
	return false
}

func (m *WalletStatus) GetIsAutoMining() bool {
	if m != nil {
		return m.IsAutoMining
	}
	return false
}

func (m *WalletStatus) GetIsHasSeed() bool {
	if m != nil {
		return m.IsHasSeed
	}
	return false
}

func (m *WalletStatus) GetIsTicketLock() bool {
	if m != nil {
		return m.IsTicketLock
	}
	return false
}

type WalletAccounts struct {
	Wallets []*WalletAccount `protobuf:"bytes,1,rep,name=wallets" json:"wallets,omitempty"`
}

func (m *WalletAccounts) Reset()                    { *m = WalletAccounts{} }
func (m *WalletAccounts) String() string            { return proto.CompactTextString(m) }
func (*WalletAccounts) ProtoMessage()               {}
func (*WalletAccounts) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{6} }

func (m *WalletAccounts) GetWallets() []*WalletAccount {
	if m != nil {
		return m.Wallets
	}
	return nil
}

type WalletAccount struct {
	Acc   *Account `protobuf:"bytes,1,opt,name=acc" json:"acc,omitempty"`
	Label string   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
}

func (m *WalletAccount) Reset()                    { *m = WalletAccount{} }
func (m *WalletAccount) String() string            { return proto.CompactTextString(m) }
func (*WalletAccount) ProtoMessage()               {}
func (*WalletAccount) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{7} }

func (m *WalletAccount) GetAcc() *Account {
	if m != nil {
		return m.Acc
	}
	return nil
}

func (m *WalletAccount) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

// 钱包解锁
// 	 passwd : 钱包密码
// 	 timeout :钱包解锁时间，0，一直解锁，非0值，超时之后继续锁定
// 	 walletOrTicket :解锁整个钱包还是只解锁挖矿买票功能，1只解锁挖矿买票，0解锁整个钱包
type WalletUnLock struct {
	Passwd         string `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
	Timeout        int64  `protobuf:"varint,2,opt,name=timeout" json:"timeout,omitempty"`
	WalletOrTicket bool   `protobuf:"varint,3,opt,name=walletOrTicket" json:"walletOrTicket,omitempty"`
}

func (m *WalletUnLock) Reset()                    { *m = WalletUnLock{} }
func (m *WalletUnLock) String() string            { return proto.CompactTextString(m) }
func (*WalletUnLock) ProtoMessage()               {}
func (*WalletUnLock) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{8} }

func (m *WalletUnLock) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *WalletUnLock) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *WalletUnLock) GetWalletOrTicket() bool {
	if m != nil {
		return m.WalletOrTicket
	}
	return false
}

type GenSeedLang struct {
	Lang int32 `protobuf:"varint,1,opt,name=lang" json:"lang,omitempty"`
}

func (m *GenSeedLang) Reset()                    { *m = GenSeedLang{} }
func (m *GenSeedLang) String() string            { return proto.CompactTextString(m) }
func (*GenSeedLang) ProtoMessage()               {}
func (*GenSeedLang) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{9} }

func (m *GenSeedLang) GetLang() int32 {
	if m != nil {
		return m.Lang
	}
	return 0
}

type GetSeedByPw struct {
	Passwd string `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *GetSeedByPw) Reset()                    { *m = GetSeedByPw{} }
func (m *GetSeedByPw) String() string            { return proto.CompactTextString(m) }
func (*GetSeedByPw) ProtoMessage()               {}
func (*GetSeedByPw) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{10} }

func (m *GetSeedByPw) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

// 存储钱包的种子
// 	 seed : 钱包种子
// 	 passwd :钱包密码
type SaveSeedByPw struct {
	Seed   string `protobuf:"bytes,1,opt,name=seed" json:"seed,omitempty"`
	Passwd string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *SaveSeedByPw) Reset()                    { *m = SaveSeedByPw{} }
func (m *SaveSeedByPw) String() string            { return proto.CompactTextString(m) }
func (*SaveSeedByPw) ProtoMessage()               {}
func (*SaveSeedByPw) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{11} }

func (m *SaveSeedByPw) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

func (m *SaveSeedByPw) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type ReplySeed struct {
	Seed string `protobuf:"bytes,1,opt,name=seed" json:"seed,omitempty"`
}

func (m *ReplySeed) Reset()                    { *m = ReplySeed{} }
func (m *ReplySeed) String() string            { return proto.CompactTextString(m) }
func (*ReplySeed) ProtoMessage()               {}
func (*ReplySeed) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{12} }

func (m *ReplySeed) GetSeed() string {
	if m != nil {
		return m.Seed
	}
	return ""
}

type ReqWalletSetPasswd struct {
	Oldpass string `protobuf:"bytes,1,opt,name=oldpass" json:"oldpass,omitempty"`
	Newpass string `protobuf:"bytes,2,opt,name=newpass" json:"newpass,omitempty"`
}

func (m *ReqWalletSetPasswd) Reset()                    { *m = ReqWalletSetPasswd{} }
func (m *ReqWalletSetPasswd) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletSetPasswd) ProtoMessage()               {}
func (*ReqWalletSetPasswd) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{13} }

func (m *ReqWalletSetPasswd) GetOldpass() string {
	if m != nil {
		return m.Oldpass
	}
	return ""
}

func (m *ReqWalletSetPasswd) GetNewpass() string {
	if m != nil {
		return m.Newpass
	}
	return ""
}

type ReqNewAccount struct {
	Label string `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *ReqNewAccount) Reset()                    { *m = ReqNewAccount{} }
func (m *ReqNewAccount) String() string            { return proto.CompactTextString(m) }
func (*ReqNewAccount) ProtoMessage()               {}
func (*ReqNewAccount) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{14} }

func (m *ReqNewAccount) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type MinerFlag struct {
	Flag    int32 `protobuf:"varint,1,opt,name=flag" json:"flag,omitempty"`
	Reserve int64 `protobuf:"varint,2,opt,name=reserve" json:"reserve,omitempty"`
}

func (m *MinerFlag) Reset()                    { *m = MinerFlag{} }
func (m *MinerFlag) String() string            { return proto.CompactTextString(m) }
func (*MinerFlag) ProtoMessage()               {}
func (*MinerFlag) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{15} }

func (m *MinerFlag) GetFlag() int32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *MinerFlag) GetReserve() int64 {
	if m != nil {
		return m.Reserve
	}
	return 0
}

// 获取钱包交易的详细信息
// 	 fromTx : []byte( Sprintf("%018d", height*100000 + index)，
// 				表示从高度 height 中的 index 开始获取交易列表；
// 			    第一次传参为空，获取最新的交易。)
// 	 count :获取交易列表的个数。
// 	 direction :查找方式；0，上一页；1，下一页。
//  mode: 查询模式，0：普通查询，1：隐私合约查询
//  sendRecvPrivacy: 查询隐私交易的发送还是接收：0：发送； 1：接收
type ReqWalletTransactionList struct {
	FromTx          []byte `protobuf:"bytes,1,opt,name=fromTx,proto3" json:"fromTx,omitempty"`
	Count           int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Direction       int32  `protobuf:"varint,3,opt,name=direction" json:"direction,omitempty"`
	Mode            int32  `protobuf:"varint,4,opt,name=mode" json:"mode,omitempty"`
	SendRecvPrivacy int32  `protobuf:"varint,5,opt,name=sendRecvPrivacy" json:"sendRecvPrivacy,omitempty"`
	// 需要查询的账号地址
	Address string `protobuf:"bytes,6,opt,name=address" json:"address,omitempty"`
}

func (m *ReqWalletTransactionList) Reset()                    { *m = ReqWalletTransactionList{} }
func (m *ReqWalletTransactionList) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletTransactionList) ProtoMessage()               {}
func (*ReqWalletTransactionList) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{16} }

func (m *ReqWalletTransactionList) GetFromTx() []byte {
	if m != nil {
		return m.FromTx
	}
	return nil
}

func (m *ReqWalletTransactionList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqWalletTransactionList) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *ReqWalletTransactionList) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *ReqWalletTransactionList) GetSendRecvPrivacy() int32 {
	if m != nil {
		return m.SendRecvPrivacy
	}
	return 0
}

func (m *ReqWalletTransactionList) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReqWalletImportPrivKey struct {
	// bitcoin 的私钥格式
	Privkey string `protobuf:"bytes,1,opt,name=privkey" json:"privkey,omitempty"`
	Label   string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
}

func (m *ReqWalletImportPrivKey) Reset()                    { *m = ReqWalletImportPrivKey{} }
func (m *ReqWalletImportPrivKey) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletImportPrivKey) ProtoMessage()               {}
func (*ReqWalletImportPrivKey) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{17} }

func (m *ReqWalletImportPrivKey) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

func (m *ReqWalletImportPrivKey) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

// 发送交易
// 	 from : 打出地址
// 	 to :接受地址
// 	 amount : 转账额度
// 	 note :转账备注
type ReqWalletSendToAddress struct {
	From        string `protobuf:"bytes,1,opt,name=from" json:"from,omitempty"`
	To          string `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Amount      int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Note        string `protobuf:"bytes,4,opt,name=note" json:"note,omitempty"`
	IsToken     bool   `protobuf:"varint,5,opt,name=isToken" json:"isToken,omitempty"`
	TokenSymbol string `protobuf:"bytes,6,opt,name=tokenSymbol" json:"tokenSymbol,omitempty"`
}

func (m *ReqWalletSendToAddress) Reset()                    { *m = ReqWalletSendToAddress{} }
func (m *ReqWalletSendToAddress) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletSendToAddress) ProtoMessage()               {}
func (*ReqWalletSendToAddress) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{18} }

func (m *ReqWalletSendToAddress) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqWalletSendToAddress) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqWalletSendToAddress) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqWalletSendToAddress) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqWalletSendToAddress) GetIsToken() bool {
	if m != nil {
		return m.IsToken
	}
	return false
}

func (m *ReqWalletSendToAddress) GetTokenSymbol() string {
	if m != nil {
		return m.TokenSymbol
	}
	return ""
}

type ReqWalletSetFee struct {
	Amount int64 `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
}

func (m *ReqWalletSetFee) Reset()                    { *m = ReqWalletSetFee{} }
func (m *ReqWalletSetFee) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletSetFee) ProtoMessage()               {}
func (*ReqWalletSetFee) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{19} }

func (m *ReqWalletSetFee) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ReqWalletSetLabel struct {
	Addr  string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
}

func (m *ReqWalletSetLabel) Reset()                    { *m = ReqWalletSetLabel{} }
func (m *ReqWalletSetLabel) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletSetLabel) ProtoMessage()               {}
func (*ReqWalletSetLabel) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{20} }

func (m *ReqWalletSetLabel) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqWalletSetLabel) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type ReqWalletMergeBalance struct {
	To string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
}

func (m *ReqWalletMergeBalance) Reset()                    { *m = ReqWalletMergeBalance{} }
func (m *ReqWalletMergeBalance) String() string            { return proto.CompactTextString(m) }
func (*ReqWalletMergeBalance) ProtoMessage()               {}
func (*ReqWalletMergeBalance) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{21} }

func (m *ReqWalletMergeBalance) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type ReqStr struct {
	ReqStr string `protobuf:"bytes,1,opt,name=reqStr" json:"reqStr,omitempty"`
}

func (m *ReqStr) Reset()                    { *m = ReqStr{} }
func (m *ReqStr) String() string            { return proto.CompactTextString(m) }
func (*ReqStr) ProtoMessage()               {}
func (*ReqStr) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{22} }

func (m *ReqStr) GetReqStr() string {
	if m != nil {
		return m.ReqStr
	}
	return ""
}

type ReplyStr struct {
	Replystr string `protobuf:"bytes,1,opt,name=replystr" json:"replystr,omitempty"`
}

func (m *ReplyStr) Reset()                    { *m = ReplyStr{} }
func (m *ReplyStr) String() string            { return proto.CompactTextString(m) }
func (*ReplyStr) ProtoMessage()               {}
func (*ReplyStr) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{23} }

func (m *ReplyStr) GetReplystr() string {
	if m != nil {
		return m.Replystr
	}
	return ""
}

type ReqTokenPreCreate struct {
	CreatorAddr  string `protobuf:"bytes,1,opt,name=creator_addr,json=creatorAddr" json:"creator_addr,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Symbol       string `protobuf:"bytes,3,opt,name=symbol" json:"symbol,omitempty"`
	Introduction string `protobuf:"bytes,4,opt,name=introduction" json:"introduction,omitempty"`
	OwnerAddr    string `protobuf:"bytes,5,opt,name=owner_addr,json=ownerAddr" json:"owner_addr,omitempty"`
	Total        int64  `protobuf:"varint,6,opt,name=total" json:"total,omitempty"`
	Price        int64  `protobuf:"varint,7,opt,name=price" json:"price,omitempty"`
}

func (m *ReqTokenPreCreate) Reset()                    { *m = ReqTokenPreCreate{} }
func (m *ReqTokenPreCreate) String() string            { return proto.CompactTextString(m) }
func (*ReqTokenPreCreate) ProtoMessage()               {}
func (*ReqTokenPreCreate) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{24} }

func (m *ReqTokenPreCreate) GetCreatorAddr() string {
	if m != nil {
		return m.CreatorAddr
	}
	return ""
}

func (m *ReqTokenPreCreate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTokenPreCreate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenPreCreate) GetIntroduction() string {
	if m != nil {
		return m.Introduction
	}
	return ""
}

func (m *ReqTokenPreCreate) GetOwnerAddr() string {
	if m != nil {
		return m.OwnerAddr
	}
	return ""
}

func (m *ReqTokenPreCreate) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReqTokenPreCreate) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ReqTokenFinishCreate struct {
	FinisherAddr string `protobuf:"bytes,1,opt,name=finisher_addr,json=finisherAddr" json:"finisher_addr,omitempty"`
	Symbol       string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	OwnerAddr    string `protobuf:"bytes,3,opt,name=owner_addr,json=ownerAddr" json:"owner_addr,omitempty"`
}

func (m *ReqTokenFinishCreate) Reset()                    { *m = ReqTokenFinishCreate{} }
func (m *ReqTokenFinishCreate) String() string            { return proto.CompactTextString(m) }
func (*ReqTokenFinishCreate) ProtoMessage()               {}
func (*ReqTokenFinishCreate) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{25} }

func (m *ReqTokenFinishCreate) GetFinisherAddr() string {
	if m != nil {
		return m.FinisherAddr
	}
	return ""
}

func (m *ReqTokenFinishCreate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenFinishCreate) GetOwnerAddr() string {
	if m != nil {
		return m.OwnerAddr
	}
	return ""
}

type ReqTokenRevokeCreate struct {
	RevokerAddr string `protobuf:"bytes,1,opt,name=revoker_addr,json=revokerAddr" json:"revoker_addr,omitempty"`
	Symbol      string `protobuf:"bytes,2,opt,name=symbol" json:"symbol,omitempty"`
	OwnerAddr   string `protobuf:"bytes,3,opt,name=owner_addr,json=ownerAddr" json:"owner_addr,omitempty"`
}

func (m *ReqTokenRevokeCreate) Reset()                    { *m = ReqTokenRevokeCreate{} }
func (m *ReqTokenRevokeCreate) String() string            { return proto.CompactTextString(m) }
func (*ReqTokenRevokeCreate) ProtoMessage()               {}
func (*ReqTokenRevokeCreate) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{26} }

func (m *ReqTokenRevokeCreate) GetRevokerAddr() string {
	if m != nil {
		return m.RevokerAddr
	}
	return ""
}

func (m *ReqTokenRevokeCreate) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqTokenRevokeCreate) GetOwnerAddr() string {
	if m != nil {
		return m.OwnerAddr
	}
	return ""
}

type ReqSellToken struct {
	Sell  *TradeForSell `protobuf:"bytes,1,opt,name=sell" json:"sell,omitempty"`
	Owner string        `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
}

func (m *ReqSellToken) Reset()                    { *m = ReqSellToken{} }
func (m *ReqSellToken) String() string            { return proto.CompactTextString(m) }
func (*ReqSellToken) ProtoMessage()               {}
func (*ReqSellToken) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{27} }

func (m *ReqSellToken) GetSell() *TradeForSell {
	if m != nil {
		return m.Sell
	}
	return nil
}

func (m *ReqSellToken) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqBuyToken struct {
	Buy   *TradeForBuy `protobuf:"bytes,1,opt,name=buy" json:"buy,omitempty"`
	Buyer string       `protobuf:"bytes,2,opt,name=buyer" json:"buyer,omitempty"`
}

func (m *ReqBuyToken) Reset()                    { *m = ReqBuyToken{} }
func (m *ReqBuyToken) String() string            { return proto.CompactTextString(m) }
func (*ReqBuyToken) ProtoMessage()               {}
func (*ReqBuyToken) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{28} }

func (m *ReqBuyToken) GetBuy() *TradeForBuy {
	if m != nil {
		return m.Buy
	}
	return nil
}

func (m *ReqBuyToken) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

type ReqRevokeSell struct {
	Revoke *TradeForRevokeSell `protobuf:"bytes,1,opt,name=revoke" json:"revoke,omitempty"`
	Owner  string              `protobuf:"bytes,2,opt,name=owner" json:"owner,omitempty"`
}

func (m *ReqRevokeSell) Reset()                    { *m = ReqRevokeSell{} }
func (m *ReqRevokeSell) String() string            { return proto.CompactTextString(m) }
func (*ReqRevokeSell) ProtoMessage()               {}
func (*ReqRevokeSell) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{29} }

func (m *ReqRevokeSell) GetRevoke() *TradeForRevokeSell {
	if m != nil {
		return m.Revoke
	}
	return nil
}

func (m *ReqRevokeSell) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ReqModifyConfig struct {
	Key      string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Op       string `protobuf:"bytes,2,opt,name=op" json:"op,omitempty"`
	Value    string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
	Modifier string `protobuf:"bytes,4,opt,name=modifier" json:"modifier,omitempty"`
}

func (m *ReqModifyConfig) Reset()                    { *m = ReqModifyConfig{} }
func (m *ReqModifyConfig) String() string            { return proto.CompactTextString(m) }
func (*ReqModifyConfig) ProtoMessage()               {}
func (*ReqModifyConfig) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{30} }

func (m *ReqModifyConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReqModifyConfig) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *ReqModifyConfig) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *ReqModifyConfig) GetModifier() string {
	if m != nil {
		return m.Modifier
	}
	return ""
}

type ReqSignRawTx struct {
	Addr    string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Privkey string `protobuf:"bytes,2,opt,name=privkey" json:"privkey,omitempty"`
	TxHex   string `protobuf:"bytes,3,opt,name=txHex" json:"txHex,omitempty"`
	Expire  string `protobuf:"bytes,4,opt,name=expire" json:"expire,omitempty"`
	Index   int32  `protobuf:"varint,5,opt,name=index" json:"index,omitempty"`
	// 签名的模式类型
	// 0：普通交易
	// 1：隐私交易
	Mode int32 `protobuf:"varint,6,opt,name=mode" json:"mode,omitempty"`
}

func (m *ReqSignRawTx) Reset()                    { *m = ReqSignRawTx{} }
func (m *ReqSignRawTx) String() string            { return proto.CompactTextString(m) }
func (*ReqSignRawTx) ProtoMessage()               {}
func (*ReqSignRawTx) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{31} }

func (m *ReqSignRawTx) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqSignRawTx) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

func (m *ReqSignRawTx) GetTxHex() string {
	if m != nil {
		return m.TxHex
	}
	return ""
}

func (m *ReqSignRawTx) GetExpire() string {
	if m != nil {
		return m.Expire
	}
	return ""
}

func (m *ReqSignRawTx) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ReqSignRawTx) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ReplySignRawTx struct {
	TxHex string `protobuf:"bytes,1,opt,name=txHex" json:"txHex,omitempty"`
}

func (m *ReplySignRawTx) Reset()                    { *m = ReplySignRawTx{} }
func (m *ReplySignRawTx) String() string            { return proto.CompactTextString(m) }
func (*ReplySignRawTx) ProtoMessage()               {}
func (*ReplySignRawTx) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{32} }

func (m *ReplySignRawTx) GetTxHex() string {
	if m != nil {
		return m.TxHex
	}
	return ""
}

type ReportErrEvent struct {
	Frommodule string `protobuf:"bytes,1,opt,name=frommodule" json:"frommodule,omitempty"`
	Tomodule   string `protobuf:"bytes,2,opt,name=tomodule" json:"tomodule,omitempty"`
	Error      string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *ReportErrEvent) Reset()                    { *m = ReportErrEvent{} }
func (m *ReportErrEvent) String() string            { return proto.CompactTextString(m) }
func (*ReportErrEvent) ProtoMessage()               {}
func (*ReportErrEvent) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{33} }

func (m *ReportErrEvent) GetFrommodule() string {
	if m != nil {
		return m.Frommodule
	}
	return ""
}

func (m *ReportErrEvent) GetTomodule() string {
	if m != nil {
		return m.Tomodule
	}
	return ""
}

func (m *ReportErrEvent) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type Int32 struct {
	Data int32 `protobuf:"varint,1,opt,name=data" json:"data,omitempty"`
}

func (m *Int32) Reset()                    { *m = Int32{} }
func (m *Int32) String() string            { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()               {}
func (*Int32) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{34} }

func (m *Int32) GetData() int32 {
	if m != nil {
		return m.Data
	}
	return 0
}

type ReqPub2Pri struct {
	// 接收人可见公钥A
	// string viewPublic  = 1;
	// 接收人花费公钥B
	// string spendPublic = 2;
	Tokenname string `protobuf:"bytes,3,opt,name=tokenname" json:"tokenname,omitempty"`
	Amount    int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Note      string `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
	// 发送人地址
	Sender     string `protobuf:"bytes,6,opt,name=sender" json:"sender,omitempty"`
	Mixin      int32  `protobuf:"varint,7,opt,name=mixin" json:"mixin,omitempty"`
	Pubkeypair string `protobuf:"bytes,8,opt,name=pubkeypair" json:"pubkeypair,omitempty"`
}

func (m *ReqPub2Pri) Reset()                    { *m = ReqPub2Pri{} }
func (m *ReqPub2Pri) String() string            { return proto.CompactTextString(m) }
func (*ReqPub2Pri) ProtoMessage()               {}
func (*ReqPub2Pri) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{35} }

func (m *ReqPub2Pri) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqPub2Pri) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqPub2Pri) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqPub2Pri) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ReqPub2Pri) GetMixin() int32 {
	if m != nil {
		return m.Mixin
	}
	return 0
}

func (m *ReqPub2Pri) GetPubkeypair() string {
	if m != nil {
		return m.Pubkeypair
	}
	return ""
}

type ReqPri2Pri struct {
	// 接收人可见公钥A
	// string viewPublic  = 1; //A
	// 接收人花费公钥B
	// string spendPublic = 2; //B
	Tokenname string `protobuf:"bytes,3,opt,name=tokenname" json:"tokenname,omitempty"`
	Amount    int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Note      string `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
	// 隐私交易发起人地址
	Sender string `protobuf:"bytes,6,opt,name=sender" json:"sender,omitempty"`
	Mixin  int32  `protobuf:"varint,7,opt,name=mixin" json:"mixin,omitempty"`
	// 	string txhash      = 7;
	Pubkeypair string `protobuf:"bytes,8,opt,name=pubkeypair" json:"pubkeypair,omitempty"`
}

func (m *ReqPri2Pri) Reset()                    { *m = ReqPri2Pri{} }
func (m *ReqPri2Pri) String() string            { return proto.CompactTextString(m) }
func (*ReqPri2Pri) ProtoMessage()               {}
func (*ReqPri2Pri) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{36} }

func (m *ReqPri2Pri) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqPri2Pri) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqPri2Pri) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqPri2Pri) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ReqPri2Pri) GetMixin() int32 {
	if m != nil {
		return m.Mixin
	}
	return 0
}

func (m *ReqPri2Pri) GetPubkeypair() string {
	if m != nil {
		return m.Pubkeypair
	}
	return ""
}

type ReqPri2Pub struct {
	Receiver  string `protobuf:"bytes,1,opt,name=receiver" json:"receiver,omitempty"`
	Tokenname string `protobuf:"bytes,2,opt,name=tokenname" json:"tokenname,omitempty"`
	Amount    int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Note      string `protobuf:"bytes,4,opt,name=note" json:"note,omitempty"`
	// 隐私交易发起人地址
	Sender string `protobuf:"bytes,5,opt,name=sender" json:"sender,omitempty"`
	Mixin  int32  `protobuf:"varint,6,opt,name=mixin" json:"mixin,omitempty"`
}

func (m *ReqPri2Pub) Reset()                    { *m = ReqPri2Pub{} }
func (m *ReqPri2Pub) String() string            { return proto.CompactTextString(m) }
func (*ReqPri2Pub) ProtoMessage()               {}
func (*ReqPri2Pub) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{37} }

func (m *ReqPri2Pub) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *ReqPri2Pub) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqPri2Pub) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqPri2Pub) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqPri2Pub) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ReqPri2Pub) GetMixin() int32 {
	if m != nil {
		return m.Mixin
	}
	return 0
}

type ReqCreateUTXOs struct {
	// string viewPublic  = 1; //接收人可见公钥A
	// string spendPublic = 2; //接收人花费公钥B
	Tokenname  string `protobuf:"bytes,3,opt,name=tokenname" json:"tokenname,omitempty"`
	Amount     int64  `protobuf:"varint,4,opt,name=amount" json:"amount,omitempty"`
	Note       string `protobuf:"bytes,5,opt,name=note" json:"note,omitempty"`
	Sender     string `protobuf:"bytes,6,opt,name=sender" json:"sender,omitempty"`
	Count      int32  `protobuf:"varint,7,opt,name=count" json:"count,omitempty"`
	Pubkeypair string `protobuf:"bytes,8,opt,name=pubkeypair" json:"pubkeypair,omitempty"`
}

func (m *ReqCreateUTXOs) Reset()                    { *m = ReqCreateUTXOs{} }
func (m *ReqCreateUTXOs) String() string            { return proto.CompactTextString(m) }
func (*ReqCreateUTXOs) ProtoMessage()               {}
func (*ReqCreateUTXOs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{38} }

func (m *ReqCreateUTXOs) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqCreateUTXOs) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqCreateUTXOs) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqCreateUTXOs) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *ReqCreateUTXOs) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReqCreateUTXOs) GetPubkeypair() string {
	if m != nil {
		return m.Pubkeypair
	}
	return ""
}

type ReplyPrivacyPkPair struct {
	ShowSuccessful bool `protobuf:"varint,1,opt,name=showSuccessful" json:"showSuccessful,omitempty"`
	// string viewPub       = 2;
	// string spendPub      = 3;
	Pubkeypair string `protobuf:"bytes,4,opt,name=pubkeypair" json:"pubkeypair,omitempty"`
}

func (m *ReplyPrivacyPkPair) Reset()                    { *m = ReplyPrivacyPkPair{} }
func (m *ReplyPrivacyPkPair) String() string            { return proto.CompactTextString(m) }
func (*ReplyPrivacyPkPair) ProtoMessage()               {}
func (*ReplyPrivacyPkPair) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{39} }

func (m *ReplyPrivacyPkPair) GetShowSuccessful() bool {
	if m != nil {
		return m.ShowSuccessful
	}
	return false
}

func (m *ReplyPrivacyPkPair) GetPubkeypair() string {
	if m != nil {
		return m.Pubkeypair
	}
	return ""
}

type ReqPrivBal4AddrToken struct {
	Addr  string `protobuf:"bytes,1,opt,name=addr" json:"addr,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *ReqPrivBal4AddrToken) Reset()                    { *m = ReqPrivBal4AddrToken{} }
func (m *ReqPrivBal4AddrToken) String() string            { return proto.CompactTextString(m) }
func (*ReqPrivBal4AddrToken) ProtoMessage()               {}
func (*ReqPrivBal4AddrToken) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{40} }

func (m *ReqPrivBal4AddrToken) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *ReqPrivBal4AddrToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReplyPrivacyBalance struct {
	Onetimeaddr string `protobuf:"bytes,1,opt,name=onetimeaddr" json:"onetimeaddr,omitempty"`
	Balance     int64  `protobuf:"varint,2,opt,name=balance" json:"balance,omitempty"`
}

func (m *ReplyPrivacyBalance) Reset()                    { *m = ReplyPrivacyBalance{} }
func (m *ReplyPrivacyBalance) String() string            { return proto.CompactTextString(m) }
func (*ReplyPrivacyBalance) ProtoMessage()               {}
func (*ReplyPrivacyBalance) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{41} }

func (m *ReplyPrivacyBalance) GetOnetimeaddr() string {
	if m != nil {
		return m.Onetimeaddr
	}
	return ""
}

func (m *ReplyPrivacyBalance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type PrivacyDBStore struct {
	Txhash           []byte `protobuf:"bytes,1,opt,name=txhash,proto3" json:"txhash,omitempty"`
	Tokenname        string `protobuf:"bytes,2,opt,name=tokenname" json:"tokenname,omitempty"`
	Amount           int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	OutIndex         int32  `protobuf:"varint,4,opt,name=outIndex" json:"outIndex,omitempty"`
	TxPublicKeyR     []byte `protobuf:"bytes,5,opt,name=txPublicKeyR,proto3" json:"txPublicKeyR,omitempty"`
	OnetimePublicKey []byte `protobuf:"bytes,6,opt,name=onetimePublicKey,proto3" json:"onetimePublicKey,omitempty"`
	Owner            string `protobuf:"bytes,7,opt,name=owner" json:"owner,omitempty"`
	Height           int64  `protobuf:"varint,8,opt,name=height" json:"height,omitempty"`
	Txindex          int32  `protobuf:"varint,9,opt,name=txindex" json:"txindex,omitempty"`
	Blockhash        []byte `protobuf:"bytes,10,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
}

func (m *PrivacyDBStore) Reset()                    { *m = PrivacyDBStore{} }
func (m *PrivacyDBStore) String() string            { return proto.CompactTextString(m) }
func (*PrivacyDBStore) ProtoMessage()               {}
func (*PrivacyDBStore) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{42} }

func (m *PrivacyDBStore) GetTxhash() []byte {
	if m != nil {
		return m.Txhash
	}
	return nil
}

func (m *PrivacyDBStore) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *PrivacyDBStore) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PrivacyDBStore) GetOutIndex() int32 {
	if m != nil {
		return m.OutIndex
	}
	return 0
}

func (m *PrivacyDBStore) GetTxPublicKeyR() []byte {
	if m != nil {
		return m.TxPublicKeyR
	}
	return nil
}

func (m *PrivacyDBStore) GetOnetimePublicKey() []byte {
	if m != nil {
		return m.OnetimePublicKey
	}
	return nil
}

func (m *PrivacyDBStore) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PrivacyDBStore) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PrivacyDBStore) GetTxindex() int32 {
	if m != nil {
		return m.Txindex
	}
	return 0
}

func (m *PrivacyDBStore) GetBlockhash() []byte {
	if m != nil {
		return m.Blockhash
	}
	return nil
}

type UTXO struct {
	Amount    int64      `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	UtxoBasic *UTXOBasic `protobuf:"bytes,2,opt,name=utxoBasic" json:"utxoBasic,omitempty"`
}

func (m *UTXO) Reset()                    { *m = UTXO{} }
func (m *UTXO) String() string            { return proto.CompactTextString(m) }
func (*UTXO) ProtoMessage()               {}
func (*UTXO) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{43} }

func (m *UTXO) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UTXO) GetUtxoBasic() *UTXOBasic {
	if m != nil {
		return m.UtxoBasic
	}
	return nil
}

type UTXOHaveTxHash struct {
	Amount    int64      `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	TxHash    string     `protobuf:"bytes,2,opt,name=txHash" json:"txHash,omitempty"`
	UtxoBasic *UTXOBasic `protobuf:"bytes,3,opt,name=utxoBasic" json:"utxoBasic,omitempty"`
}

func (m *UTXOHaveTxHash) Reset()                    { *m = UTXOHaveTxHash{} }
func (m *UTXOHaveTxHash) String() string            { return proto.CompactTextString(m) }
func (*UTXOHaveTxHash) ProtoMessage()               {}
func (*UTXOHaveTxHash) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{44} }

func (m *UTXOHaveTxHash) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UTXOHaveTxHash) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *UTXOHaveTxHash) GetUtxoBasic() *UTXOBasic {
	if m != nil {
		return m.UtxoBasic
	}
	return nil
}

type UTXOs struct {
	Utxos []*UTXO `protobuf:"bytes,1,rep,name=utxos" json:"utxos,omitempty"`
}

func (m *UTXOs) Reset()                    { *m = UTXOs{} }
func (m *UTXOs) String() string            { return proto.CompactTextString(m) }
func (*UTXOs) ProtoMessage()               {}
func (*UTXOs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{45} }

func (m *UTXOs) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type UTXOHaveTxHashs struct {
	UtxoHaveTxHashs []*UTXOHaveTxHash `protobuf:"bytes,1,rep,name=utxoHaveTxHashs" json:"utxoHaveTxHashs,omitempty"`
}

func (m *UTXOHaveTxHashs) Reset()                    { *m = UTXOHaveTxHashs{} }
func (m *UTXOHaveTxHashs) String() string            { return proto.CompactTextString(m) }
func (*UTXOHaveTxHashs) ProtoMessage()               {}
func (*UTXOHaveTxHashs) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{46} }

func (m *UTXOHaveTxHashs) GetUtxoHaveTxHashs() []*UTXOHaveTxHash {
	if m != nil {
		return m.UtxoHaveTxHashs
	}
	return nil
}

type ReqUTXOGlobalIndex struct {
	Tokenname string  `protobuf:"bytes,1,opt,name=tokenname" json:"tokenname,omitempty"`
	MixCount  int32   `protobuf:"varint,2,opt,name=mixCount" json:"mixCount,omitempty"`
	Amount    []int64 `protobuf:"varint,3,rep,packed,name=amount" json:"amount,omitempty"`
}

func (m *ReqUTXOGlobalIndex) Reset()                    { *m = ReqUTXOGlobalIndex{} }
func (m *ReqUTXOGlobalIndex) String() string            { return proto.CompactTextString(m) }
func (*ReqUTXOGlobalIndex) ProtoMessage()               {}
func (*ReqUTXOGlobalIndex) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{47} }

func (m *ReqUTXOGlobalIndex) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqUTXOGlobalIndex) GetMixCount() int32 {
	if m != nil {
		return m.MixCount
	}
	return 0
}

func (m *ReqUTXOGlobalIndex) GetAmount() []int64 {
	if m != nil {
		return m.Amount
	}
	return nil
}

type UTXOBasic struct {
	UtxoGlobalIndex *UTXOGlobalIndex `protobuf:"bytes,1,opt,name=utxoGlobalIndex" json:"utxoGlobalIndex,omitempty"`
	OnetimePubkey   []byte           `protobuf:"bytes,2,opt,name=onetimePubkey,proto3" json:"onetimePubkey,omitempty"`
}

func (m *UTXOBasic) Reset()                    { *m = UTXOBasic{} }
func (m *UTXOBasic) String() string            { return proto.CompactTextString(m) }
func (*UTXOBasic) ProtoMessage()               {}
func (*UTXOBasic) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{48} }

func (m *UTXOBasic) GetUtxoGlobalIndex() *UTXOGlobalIndex {
	if m != nil {
		return m.UtxoGlobalIndex
	}
	return nil
}

func (m *UTXOBasic) GetOnetimePubkey() []byte {
	if m != nil {
		return m.OnetimePubkey
	}
	return nil
}

type UTXOIndex4Amount struct {
	Amount int64        `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	Utxos  []*UTXOBasic `protobuf:"bytes,2,rep,name=utxos" json:"utxos,omitempty"`
}

func (m *UTXOIndex4Amount) Reset()                    { *m = UTXOIndex4Amount{} }
func (m *UTXOIndex4Amount) String() string            { return proto.CompactTextString(m) }
func (*UTXOIndex4Amount) ProtoMessage()               {}
func (*UTXOIndex4Amount) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{49} }

func (m *UTXOIndex4Amount) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *UTXOIndex4Amount) GetUtxos() []*UTXOBasic {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type ResUTXOGlobalIndex struct {
	Tokenname        string              `protobuf:"bytes,1,opt,name=tokenname" json:"tokenname,omitempty"`
	MixCount         int32               `protobuf:"varint,2,opt,name=mixCount" json:"mixCount,omitempty"`
	UtxoIndex4Amount []*UTXOIndex4Amount `protobuf:"bytes,3,rep,name=utxoIndex4Amount" json:"utxoIndex4Amount,omitempty"`
}

func (m *ResUTXOGlobalIndex) Reset()                    { *m = ResUTXOGlobalIndex{} }
func (m *ResUTXOGlobalIndex) String() string            { return proto.CompactTextString(m) }
func (*ResUTXOGlobalIndex) ProtoMessage()               {}
func (*ResUTXOGlobalIndex) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{50} }

func (m *ResUTXOGlobalIndex) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ResUTXOGlobalIndex) GetMixCount() int32 {
	if m != nil {
		return m.MixCount
	}
	return 0
}

func (m *ResUTXOGlobalIndex) GetUtxoIndex4Amount() []*UTXOIndex4Amount {
	if m != nil {
		return m.UtxoIndex4Amount
	}
	return nil
}

type FTXOsSTXOsInOneTx struct {
	Tokenname  string  `protobuf:"bytes,1,opt,name=tokenname" json:"tokenname,omitempty"`
	Sender     string  `protobuf:"bytes,2,opt,name=sender" json:"sender,omitempty"`
	TimeoutSec int32   `protobuf:"varint,3,opt,name=timeoutSec" json:"timeoutSec,omitempty"`
	Txhash     string  `protobuf:"bytes,4,opt,name=txhash" json:"txhash,omitempty"`
	Utxos      []*UTXO `protobuf:"bytes,5,rep,name=utxos" json:"utxos,omitempty"`
}

func (m *FTXOsSTXOsInOneTx) Reset()                    { *m = FTXOsSTXOsInOneTx{} }
func (m *FTXOsSTXOsInOneTx) String() string            { return proto.CompactTextString(m) }
func (*FTXOsSTXOsInOneTx) ProtoMessage()               {}
func (*FTXOsSTXOsInOneTx) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{51} }

func (m *FTXOsSTXOsInOneTx) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *FTXOsSTXOsInOneTx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *FTXOsSTXOsInOneTx) GetTimeoutSec() int32 {
	if m != nil {
		return m.TimeoutSec
	}
	return 0
}

func (m *FTXOsSTXOsInOneTx) GetTxhash() string {
	if m != nil {
		return m.Txhash
	}
	return ""
}

func (m *FTXOsSTXOsInOneTx) GetUtxos() []*UTXO {
	if m != nil {
		return m.Utxos
	}
	return nil
}

// 某些交易需要存在一些复杂的算法，所以需要请求服务器协助构建交易，返回对应交易哈希值，后续签名可以根据此哈希值进行处理
type ReqCreateTransaction struct {
	Tokenname string `protobuf:"bytes,1,opt,name=tokenname" json:"tokenname,omitempty"`
	// 构建交易类型
	// 0：普通的交易（暂不支持）
	// 1：隐私交易 公开->隐私
	// 2：隐私交易 隐私->隐私
	// 3：隐私交易 隐私->公开
	Type   int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Amount int64  `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	Note   string `protobuf:"bytes,4,opt,name=note" json:"note,omitempty"`
	// 普通交易的发送方
	From string `protobuf:"bytes,5,opt,name=from" json:"from,omitempty"`
	// 普通交易的接收方
	To string `protobuf:"bytes,6,opt,name=to" json:"to,omitempty"`
	// 隐私交易，接收方的公钥对
	Pubkeypair string `protobuf:"bytes,10,opt,name=pubkeypair" json:"pubkeypair,omitempty"`
	Mixcount   int32  `protobuf:"varint,11,opt,name=mixcount" json:"mixcount,omitempty"`
}

func (m *ReqCreateTransaction) Reset()                    { *m = ReqCreateTransaction{} }
func (m *ReqCreateTransaction) String() string            { return proto.CompactTextString(m) }
func (*ReqCreateTransaction) ProtoMessage()               {}
func (*ReqCreateTransaction) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{52} }

func (m *ReqCreateTransaction) GetTokenname() string {
	if m != nil {
		return m.Tokenname
	}
	return ""
}

func (m *ReqCreateTransaction) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqCreateTransaction) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqCreateTransaction) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *ReqCreateTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqCreateTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqCreateTransaction) GetPubkeypair() string {
	if m != nil {
		return m.Pubkeypair
	}
	return ""
}

func (m *ReqCreateTransaction) GetMixcount() int32 {
	if m != nil {
		return m.Mixcount
	}
	return 0
}

type RealKeyInput struct {
	Realinputkey   int32  `protobuf:"varint,1,opt,name=realinputkey" json:"realinputkey,omitempty"`
	Onetimeprivkey []byte `protobuf:"bytes,2,opt,name=onetimeprivkey,proto3" json:"onetimeprivkey,omitempty"`
}

func (m *RealKeyInput) Reset()                    { *m = RealKeyInput{} }
func (m *RealKeyInput) String() string            { return proto.CompactTextString(m) }
func (*RealKeyInput) ProtoMessage()               {}
func (*RealKeyInput) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{53} }

func (m *RealKeyInput) GetRealinputkey() int32 {
	if m != nil {
		return m.Realinputkey
	}
	return 0
}

func (m *RealKeyInput) GetOnetimeprivkey() []byte {
	if m != nil {
		return m.Onetimeprivkey
	}
	return nil
}

type UTXOBasics struct {
	Utxos []*UTXOBasic `protobuf:"bytes,1,rep,name=utxos" json:"utxos,omitempty"`
}

func (m *UTXOBasics) Reset()                    { *m = UTXOBasics{} }
func (m *UTXOBasics) String() string            { return proto.CompactTextString(m) }
func (*UTXOBasics) ProtoMessage()               {}
func (*UTXOBasics) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{54} }

func (m *UTXOBasics) GetUtxos() []*UTXOBasic {
	if m != nil {
		return m.Utxos
	}
	return nil
}

type CreateTransactionCache struct {
	// 记录创建时间，用以处理过期的交易
	Createtime int64 `protobuf:"varint,1,opt,name=createtime" json:"createtime,omitempty"`
	// 记录签名成功的时间，用以处理过期交易
	Signtime int64 `protobuf:"varint,2,opt,name=signtime" json:"signtime,omitempty"`
	// 缓存状态
	// 0 - 创建状态
	// 1 - 已经签名状态
	Status int32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	//
	Transaction  *Transaction    `protobuf:"bytes,4,opt,name=transaction" json:"transaction,omitempty"`
	Sender       string          `protobuf:"bytes,5,opt,name=sender" json:"sender,omitempty"`
	Realkeyinput []*RealKeyInput `protobuf:"bytes,6,rep,name=realkeyinput" json:"realkeyinput,omitempty"`
	Utxos        []*UTXOBasics   `protobuf:"bytes,7,rep,name=utxos" json:"utxos,omitempty"`
}

func (m *CreateTransactionCache) Reset()                    { *m = CreateTransactionCache{} }
func (m *CreateTransactionCache) String() string            { return proto.CompactTextString(m) }
func (*CreateTransactionCache) ProtoMessage()               {}
func (*CreateTransactionCache) Descriptor() ([]byte, []int) { return fileDescriptor13, []int{55} }

func (m *CreateTransactionCache) GetCreatetime() int64 {
	if m != nil {
		return m.Createtime
	}
	return 0
}

func (m *CreateTransactionCache) GetSigntime() int64 {
	if m != nil {
		return m.Signtime
	}
	return 0
}

func (m *CreateTransactionCache) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateTransactionCache) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *CreateTransactionCache) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *CreateTransactionCache) GetRealkeyinput() []*RealKeyInput {
	if m != nil {
		return m.Realkeyinput
	}
	return nil
}

func (m *CreateTransactionCache) GetUtxos() []*UTXOBasics {
	if m != nil {
		return m.Utxos
	}
	return nil
}

func init() {
	proto.RegisterType((*WalletTxDetail)(nil), "types.WalletTxDetail")
	proto.RegisterType((*WalletTxDetails)(nil), "types.WalletTxDetails")
	proto.RegisterType((*WalletAccountStore)(nil), "types.WalletAccountStore")
	proto.RegisterType((*WalletAccountPrivacy)(nil), "types.WalletAccountPrivacy")
	proto.RegisterType((*WalletPwHash)(nil), "types.WalletPwHash")
	proto.RegisterType((*WalletStatus)(nil), "types.WalletStatus")
	proto.RegisterType((*WalletAccounts)(nil), "types.WalletAccounts")
	proto.RegisterType((*WalletAccount)(nil), "types.WalletAccount")
	proto.RegisterType((*WalletUnLock)(nil), "types.WalletUnLock")
	proto.RegisterType((*GenSeedLang)(nil), "types.GenSeedLang")
	proto.RegisterType((*GetSeedByPw)(nil), "types.GetSeedByPw")
	proto.RegisterType((*SaveSeedByPw)(nil), "types.SaveSeedByPw")
	proto.RegisterType((*ReplySeed)(nil), "types.ReplySeed")
	proto.RegisterType((*ReqWalletSetPasswd)(nil), "types.ReqWalletSetPasswd")
	proto.RegisterType((*ReqNewAccount)(nil), "types.ReqNewAccount")
	proto.RegisterType((*MinerFlag)(nil), "types.MinerFlag")
	proto.RegisterType((*ReqWalletTransactionList)(nil), "types.ReqWalletTransactionList")
	proto.RegisterType((*ReqWalletImportPrivKey)(nil), "types.ReqWalletImportPrivKey")
	proto.RegisterType((*ReqWalletSendToAddress)(nil), "types.ReqWalletSendToAddress")
	proto.RegisterType((*ReqWalletSetFee)(nil), "types.ReqWalletSetFee")
	proto.RegisterType((*ReqWalletSetLabel)(nil), "types.ReqWalletSetLabel")
	proto.RegisterType((*ReqWalletMergeBalance)(nil), "types.ReqWalletMergeBalance")
	proto.RegisterType((*ReqStr)(nil), "types.ReqStr")
	proto.RegisterType((*ReplyStr)(nil), "types.ReplyStr")
	proto.RegisterType((*ReqTokenPreCreate)(nil), "types.ReqTokenPreCreate")
	proto.RegisterType((*ReqTokenFinishCreate)(nil), "types.ReqTokenFinishCreate")
	proto.RegisterType((*ReqTokenRevokeCreate)(nil), "types.ReqTokenRevokeCreate")
	proto.RegisterType((*ReqSellToken)(nil), "types.ReqSellToken")
	proto.RegisterType((*ReqBuyToken)(nil), "types.ReqBuyToken")
	proto.RegisterType((*ReqRevokeSell)(nil), "types.ReqRevokeSell")
	proto.RegisterType((*ReqModifyConfig)(nil), "types.ReqModifyConfig")
	proto.RegisterType((*ReqSignRawTx)(nil), "types.ReqSignRawTx")
	proto.RegisterType((*ReplySignRawTx)(nil), "types.ReplySignRawTx")
	proto.RegisterType((*ReportErrEvent)(nil), "types.ReportErrEvent")
	proto.RegisterType((*Int32)(nil), "types.Int32")
	proto.RegisterType((*ReqPub2Pri)(nil), "types.ReqPub2Pri")
	proto.RegisterType((*ReqPri2Pri)(nil), "types.ReqPri2Pri")
	proto.RegisterType((*ReqPri2Pub)(nil), "types.ReqPri2Pub")
	proto.RegisterType((*ReqCreateUTXOs)(nil), "types.ReqCreateUTXOs")
	proto.RegisterType((*ReplyPrivacyPkPair)(nil), "types.ReplyPrivacyPkPair")
	proto.RegisterType((*ReqPrivBal4AddrToken)(nil), "types.ReqPrivBal4AddrToken")
	proto.RegisterType((*ReplyPrivacyBalance)(nil), "types.ReplyPrivacyBalance")
	proto.RegisterType((*PrivacyDBStore)(nil), "types.PrivacyDBStore")
	proto.RegisterType((*UTXO)(nil), "types.UTXO")
	proto.RegisterType((*UTXOHaveTxHash)(nil), "types.UTXOHaveTxHash")
	proto.RegisterType((*UTXOs)(nil), "types.UTXOs")
	proto.RegisterType((*UTXOHaveTxHashs)(nil), "types.UTXOHaveTxHashs")
	proto.RegisterType((*ReqUTXOGlobalIndex)(nil), "types.ReqUTXOGlobalIndex")
	proto.RegisterType((*UTXOBasic)(nil), "types.UTXOBasic")
	proto.RegisterType((*UTXOIndex4Amount)(nil), "types.UTXOIndex4Amount")
	proto.RegisterType((*ResUTXOGlobalIndex)(nil), "types.ResUTXOGlobalIndex")
	proto.RegisterType((*FTXOsSTXOsInOneTx)(nil), "types.FTXOsSTXOsInOneTx")
	proto.RegisterType((*ReqCreateTransaction)(nil), "types.ReqCreateTransaction")
	proto.RegisterType((*RealKeyInput)(nil), "types.RealKeyInput")
	proto.RegisterType((*UTXOBasics)(nil), "types.UTXOBasics")
	proto.RegisterType((*CreateTransactionCache)(nil), "types.CreateTransactionCache")
}

func init() { proto.RegisterFile("wallet.proto", fileDescriptor13) }

var fileDescriptor13 = []byte{
	// 2168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x5f, 0x6f, 0x1c, 0x49,
	0x11, 0xd7, 0xec, 0x1f, 0xdb, 0x5b, 0xbb, 0x71, 0x9c, 0x49, 0x2e, 0x2c, 0x01, 0x0e, 0xa7, 0xb9,
	0x4b, 0x7c, 0x27, 0x14, 0x89, 0x24, 0x12, 0x02, 0x09, 0x91, 0x38, 0x39, 0xc7, 0x56, 0xe2, 0x64,
	0xe9, 0xdd, 0x13, 0x27, 0x84, 0x84, 0x7a, 0x67, 0xdb, 0xf6, 0xc8, 0xb3, 0x33, 0xeb, 0x9e, 0x9e,
	0xfd, 0xf3, 0x39, 0xe0, 0x81, 0x07, 0x84, 0x78, 0xe0, 0x81, 0x47, 0x3e, 0x01, 0xdf, 0x80, 0x07,
	0x24, 0x3e, 0x10, 0xaa, 0xea, 0xee, 0x99, 0x9e, 0xb5, 0x8d, 0x75, 0x80, 0xd0, 0xbd, 0x8c, 0xfa,
	0x57, 0x5d, 0x5d, 0x5d, 0xf5, 0xeb, 0x9a, 0xea, 0x3f, 0xd0, 0x5b, 0x88, 0x24, 0x91, 0xfa, 0xc9,
	0x4c, 0x65, 0x3a, 0x0b, 0xdb, 0x7a, 0x35, 0x93, 0xf9, 0x83, 0x3b, 0x5a, 0x89, 0x34, 0x17, 0x91,
	0x8e, 0xb3, 0xd4, 0xf4, 0x3c, 0xd8, 0x19, 0x27, 0x59, 0x74, 0x1e, 0x9d, 0x89, 0xd8, 0x49, 0x6e,
	0x89, 0x28, 0xca, 0x8a, 0xd4, 0x0e, 0x7d, 0xb0, 0x2d, 0x97, 0x32, 0x2a, 0x74, 0xa6, 0x2c, 0xbe,
	0xeb, 0xf0, 0x48, 0x89, 0x89, 0x34, 0x42, 0xf6, 0xf7, 0x06, 0x6c, 0xff, 0x92, 0x26, 0x1c, 0x2d,
	0x5f, 0x4b, 0x2d, 0xe2, 0x24, 0x64, 0xd0, 0xd0, 0xcb, 0x7e, 0xb0, 0x1b, 0xec, 0x75, 0x9f, 0x86,
	0x4f, 0x68, 0xfe, 0x27, 0xa3, 0x6a, 0x7a, 0xde, 0xd0, 0xcb, 0xf0, 0x87, 0xb0, 0xa9, 0x64, 0x24,
	0xe3, 0x99, 0xee, 0x37, 0x6a, 0x8a, 0xdc, 0x48, 0x5f, 0x0b, 0x2d, 0xb8, 0x53, 0x09, 0xef, 0xc3,
	0xc6, 0x99, 0x8c, 0x4f, 0xcf, 0x74, 0xbf, 0xb9, 0x1b, 0xec, 0x35, 0xb9, 0x45, 0xe1, 0x3d, 0x68,
	0xc7, 0xe9, 0x44, 0x2e, 0xfb, 0x2d, 0x12, 0x1b, 0x10, 0x7e, 0x17, 0x3a, 0x14, 0x9a, 0x8e, 0xa7,
	0xb2, 0xdf, 0xa6, 0x9e, 0x4a, 0x80, 0xb6, 0xc4, 0x14, 0xa3, 0xec, 0x6f, 0x18, 0x5b, 0x06, 0x85,
	0x0c, 0x7a, 0xb9, 0x4c, 0x27, 0x52, 0x71, 0x19, 0xcd, 0xa5, 0xea, 0x6f, 0xee, 0x06, 0x7b, 0x1d,
	0x5e, 0x93, 0xe1, 0x58, 0xbd, 0x3c, 0x13, 0xf9, 0x59, 0x7f, 0x6b, 0x37, 0xd8, 0xeb, 0x71, 0x8b,
	0xc2, 0x8f, 0x01, 0x4c, 0x6c, 0xef, 0xc5, 0x54, 0xf6, 0x3b, 0x34, 0xd2, 0x93, 0x84, 0x9f, 0x41,
	0x27, 0x9f, 0xc9, 0x74, 0xa2, 0x64, 0x34, 0xef, 0xc3, 0x6e, 0x73, 0xaf, 0xfb, 0xb4, 0x6b, 0xe3,
	0xfd, 0x72, 0xf4, 0xd5, 0x07, 0x5e, 0xf5, 0xb2, 0x03, 0xb8, 0x5d, 0xa7, 0x33, 0x0f, 0x9f, 0x41,
	0x47, 0x3b, 0xd0, 0x0f, 0x68, 0xf4, 0x47, 0x76, 0x74, 0x5d, 0x95, 0x57, 0x7a, 0x6c, 0x0e, 0xa1,
	0xe9, 0x7c, 0x69, 0xd6, 0x74, 0xa8, 0x33, 0x25, 0xc3, 0x3e, 0x6c, 0xce, 0x54, 0x3c, 0x3f, 0x97,
	0x2b, 0x5a, 0x9f, 0x0e, 0x77, 0x10, 0xa9, 0x4c, 0xc4, 0x58, 0x26, 0xb4, 0x1c, 0x1d, 0x6e, 0x40,
	0x18, 0x42, 0x4b, 0x4c, 0x26, 0x8a, 0x68, 0xef, 0x70, 0x6a, 0x23, 0xbd, 0x48, 0xe4, 0x50, 0x8b,
	0xe9, 0x8c, 0x88, 0xef, 0xf0, 0x4a, 0xc0, 0xfe, 0x18, 0xc0, 0xbd, 0xda, 0xc4, 0x03, 0x15, 0xcf,
	0x45, 0xb4, 0x42, 0x8e, 0xe6, 0xb1, 0x5c, 0x0c, 0x8a, 0xb1, 0x9b, 0xbd, 0xc7, 0x3d, 0x49, 0xb8,
	0x0b, 0x5d, 0x42, 0x2a, 0x9e, 0xbf, 0x95, 0x2b, 0x72, 0xa3, 0xc7, 0x7d, 0x11, 0x6a, 0x10, 0x4f,
	0xd6, 0x44, 0xd3, 0x68, 0x78, 0x22, 0x5a, 0x43, 0x82, 0xd6, 0x48, 0x8b, 0x54, 0x6a, 0x32, 0xf6,
	0x02, 0x7a, 0xc6, 0xbf, 0xc1, 0xe2, 0x10, 0xd7, 0xee, 0x3e, 0x6c, 0xcc, 0xa8, 0x65, 0x7d, 0xb2,
	0x08, 0xa9, 0x52, 0x22, 0x9d, 0xe4, 0x5a, 0x59, 0x4a, 0x1c, 0x64, 0xbf, 0x0f, 0x9c, 0x89, 0xa1,
	0x16, 0xba, 0xc8, 0x71, 0xda, 0x38, 0x37, 0x92, 0x77, 0x59, 0x74, 0x4e, 0x86, 0xb6, 0x78, 0x4d,
	0x66, 0x74, 0x5e, 0x16, 0x3a, 0x3b, 0x8e, 0xd3, 0x38, 0x3d, 0x25, 0x9b, 0xa4, 0x53, 0xc9, 0x90,
	0xd9, 0x38, 0x3f, 0x14, 0xf9, 0x50, 0xca, 0x09, 0x85, 0xb7, 0xc5, 0x2b, 0x81, 0xb1, 0x30, 0x8a,
	0xa3, 0x73, 0x3b, 0x4b, 0xcb, 0x59, 0xa8, 0x64, 0xec, 0x85, 0xfb, 0x19, 0x2d, 0xf9, 0x79, 0xf8,
	0x04, 0x36, 0x4d, 0x3d, 0x70, 0xa9, 0x73, 0xaf, 0x96, 0x3a, 0x56, 0x8f, 0x3b, 0x25, 0xf6, 0x06,
	0x6e, 0xd5, 0x7a, 0xc2, 0x5d, 0x68, 0x8a, 0x28, 0xb2, 0xbf, 0xf3, 0xb6, 0x1d, 0xec, 0x86, 0x61,
	0xd7, 0xd5, 0xa9, 0xc3, 0xce, 0x1c, 0x49, 0x5f, 0xa6, 0x44, 0x00, 0xf2, 0x2c, 0xf2, 0x7c, 0x31,
	0xb1, 0x99, 0x67, 0x11, 0xf2, 0x8c, 0xd9, 0x93, 0x15, 0xa6, 0x12, 0x34, 0xb9, 0x83, 0xe1, 0x23,
	0xd8, 0x36, 0x5e, 0x7d, 0x50, 0x26, 0x44, 0xcb, 0xc9, 0x9a, 0x94, 0x3d, 0x84, 0xee, 0x1b, 0x99,
	0x22, 0x47, 0xef, 0x44, 0x7a, 0x8a, 0x39, 0x9b, 0x88, 0xf4, 0x94, 0xa6, 0x69, 0x73, 0x6a, 0xb3,
	0x4f, 0x51, 0x45, 0xa3, 0xca, 0xfe, 0x6a, 0xb0, 0xb8, 0xce, 0x17, 0xf6, 0x53, 0xe8, 0x0d, 0xc5,
	0x5c, 0x96, 0x7a, 0x21, 0xb4, 0x72, 0x5c, 0x0b, 0xa3, 0x45, 0x6d, 0x6f, 0x6c, 0xa3, 0x36, 0xf6,
	0xfb, 0xd0, 0xe1, 0x72, 0x96, 0xac, 0x68, 0xad, 0xae, 0x18, 0xc8, 0x0e, 0x21, 0xe4, 0xf2, 0xc2,
	0x26, 0x8e, 0xd4, 0x83, 0x32, 0xfc, 0x2c, 0x99, 0xa0, 0x0d, 0xf7, 0x47, 0x5a, 0x88, 0x3d, 0xa9,
	0x5c, 0x50, 0x8f, 0x4d, 0x40, 0x0b, 0xd9, 0xa7, 0x70, 0x8b, 0xcb, 0x8b, 0xf7, 0x72, 0xe1, 0xd6,
	0xa8, 0x5c, 0x81, 0xc0, 0x5f, 0x81, 0x9f, 0x40, 0xe7, 0x38, 0x4e, 0xa5, 0x3a, 0x48, 0x04, 0xb1,
	0x72, 0x92, 0x88, 0x92, 0x15, 0x6c, 0x53, 0x8a, 0xcb, 0x5c, 0xaa, 0xb9, 0x74, 0xd4, 0x5b, 0xc8,
	0xfe, 0x16, 0x40, 0xbf, 0x74, 0xd6, 0xab, 0xdd, 0xef, 0xe2, 0x9c, 0xaa, 0xf1, 0x89, 0xca, 0xa6,
	0xa3, 0xa5, 0xfb, 0x63, 0x0c, 0x42, 0x2f, 0xc8, 0x1d, 0x32, 0xd6, 0xe6, 0x06, 0x60, 0x52, 0x4f,
	0x62, 0x25, 0x69, 0x38, 0x2d, 0x60, 0x9b, 0x57, 0x02, 0x74, 0x6b, 0x9a, 0x4d, 0x24, 0x25, 0x73,
	0x9b, 0x53, 0x3b, 0xdc, 0x83, 0xdb, 0x58, 0x75, 0xb1, 0xe6, 0xda, 0xe2, 0x41, 0x55, 0xbc, 0xcd,
	0xd7, 0xc5, 0x18, 0x00, 0x96, 0x24, 0x99, 0xe7, 0x54, 0xcc, 0x3b, 0xdc, 0x41, 0x76, 0x08, 0xf7,
	0x4b, 0xff, 0x8f, 0xa6, 0xb3, 0x4c, 0x69, 0x57, 0x45, 0xbe, 0x66, 0x09, 0x64, 0x7f, 0x0e, 0x3c,
	0x53, 0x43, 0x99, 0x4e, 0x46, 0xd9, 0x4b, 0x33, 0x09, 0x71, 0xaa, 0xb2, 0xa9, 0x5b, 0x65, 0x6c,
	0x87, 0xdb, 0xd0, 0xd0, 0x99, 0xb5, 0xd0, 0xd0, 0x99, 0xb7, 0xdd, 0x34, 0x6b, 0xdb, 0x4d, 0x08,
	0xad, 0x34, 0xd3, 0xd2, 0x16, 0x50, 0x6a, 0xa3, 0x6b, 0x71, 0x3e, 0xca, 0xce, 0x65, 0x4a, 0x01,
	0x6f, 0x71, 0x07, 0xb1, 0xf4, 0x69, 0x6c, 0x0c, 0x57, 0xd3, 0x71, 0x96, 0xd8, 0x60, 0x7d, 0x11,
	0xfb, 0x0c, 0x6e, 0xfb, 0xd9, 0x75, 0x20, 0xfd, 0x9d, 0x2e, 0xf0, 0xa7, 0x66, 0x3f, 0x83, 0x3b,
	0xbe, 0xea, 0xbb, 0x5a, 0xa5, 0x0f, 0xbc, 0x4a, 0x7f, 0x35, 0x21, 0x8f, 0xe1, 0xa3, 0x72, 0xf8,
	0xb1, 0x54, 0xa7, 0x72, 0x5f, 0x24, 0x22, 0x8d, 0xa4, 0x0d, 0x3d, 0x70, 0xa1, 0xb3, 0x5d, 0xd8,
	0xe0, 0xf2, 0x62, 0xa8, 0x69, 0xdf, 0x54, 0xd4, 0x72, 0xff, 0x9b, 0x41, 0xec, 0x11, 0x6c, 0x99,
	0x7f, 0x46, 0xab, 0xf0, 0x01, 0x6c, 0x29, 0x6c, 0xe7, 0xa5, 0x56, 0x89, 0xd9, 0x3f, 0x02, 0x72,
	0x99, 0xb8, 0x18, 0x28, 0xf9, 0x4a, 0x49, 0xa1, 0x65, 0xf8, 0x10, 0x7a, 0x11, 0xb6, 0x32, 0xf5,
	0x1b, 0xcf, 0xf5, 0xae, 0x95, 0xe1, 0x22, 0x11, 0xcb, 0xb8, 0x25, 0x37, 0x2c, 0xcb, 0xc2, 0x1c,
	0x00, 0x72, 0x43, 0xa3, 0xd9, 0xd5, 0x2c, 0xa2, 0xfa, 0x9a, 0x6a, 0x95, 0x4d, 0x0a, 0x93, 0xab,
	0x66, 0x65, 0x6a, 0xb2, 0xf0, 0x7b, 0x00, 0xd9, 0x22, 0x95, 0x76, 0xc2, 0xb6, 0xd9, 0xfc, 0x48,
	0xf2, 0xd2, 0x12, 0xa6, 0x33, 0x2d, 0x12, 0x7b, 0xb4, 0x30, 0x00, 0xa5, 0x33, 0x15, 0x47, 0x92,
	0x8e, 0x14, 0x4d, 0x6e, 0x00, 0x53, 0x70, 0xcf, 0x85, 0x74, 0x10, 0xa7, 0x71, 0x7e, 0x66, 0xa3,
	0xfa, 0x01, 0xdc, 0x3a, 0x21, 0x2c, 0x6b, 0x61, 0xf5, 0x9c, 0x90, 0x26, 0xaa, 0x62, 0x68, 0xd4,
	0x62, 0xa8, 0xfb, 0xd7, 0x5c, 0xf3, 0x8f, 0xcd, 0xaa, 0x39, 0xb9, 0x9c, 0x67, 0xe7, 0x1e, 0x93,
	0x8a, 0x70, 0x9d, 0x49, 0x2b, 0xfb, 0x6f, 0x66, 0x3c, 0x86, 0x1e, 0xe6, 0x80, 0x4c, 0x12, 0x93,
	0xc8, 0x8f, 0xb1, 0x30, 0x26, 0x89, 0xdd, 0x4e, 0xee, 0x56, 0xa7, 0xc3, 0x89, 0x3c, 0xc8, 0x14,
	0xea, 0x71, 0x52, 0x40, 0xd2, 0xc8, 0x8a, 0xcb, 0x3d, 0x02, 0xec, 0x08, 0xba, 0x5c, 0x5e, 0xec,
	0x17, 0x2b, 0x63, 0xed, 0x13, 0x68, 0x8e, 0x8b, 0xd5, 0xe5, 0xa3, 0x26, 0x19, 0xdb, 0x2f, 0x56,
	0x1c, 0xbb, 0xd1, 0xd4, 0xb8, 0x58, 0x55, 0xa6, 0x08, 0xb0, 0xaf, 0xa8, 0x88, 0x1a, 0x1a, 0x70,
	0xde, 0xf0, 0x47, 0x98, 0xa4, 0x88, 0xac, 0xbd, 0x6f, 0xaf, 0xd9, 0xab, 0x54, 0xb9, 0x55, 0xbc,
	0xc6, 0x49, 0x49, 0xbf, 0xe2, 0x71, 0x36, 0x89, 0x4f, 0x56, 0xaf, 0xb2, 0xf4, 0x24, 0x3e, 0x0d,
	0x77, 0xa0, 0x59, 0x15, 0x1c, 0x6c, 0xe2, 0xcf, 0x92, 0xcd, 0x5c, 0x9d, 0xc8, 0x66, 0x68, 0x6a,
	0x2e, 0x92, 0x42, 0x5a, 0x0a, 0x0d, 0xc0, 0x9f, 0x62, 0x8a, 0x76, 0x62, 0xa9, 0x6c, 0x3e, 0x96,
	0x98, 0xfd, 0x2e, 0x30, 0xdc, 0xc6, 0xa7, 0x29, 0x17, 0x8b, 0xd1, 0xf2, 0xca, 0x5f, 0xd8, 0xab,
	0x76, 0x8d, 0x4b, 0xd5, 0x4e, 0x2f, 0x0f, 0xe5, 0xd2, 0x4d, 0x48, 0x00, 0x97, 0x59, 0x2e, 0x67,
	0xb1, 0x72, 0x85, 0xc9, 0xa2, 0xea, 0xa4, 0x6d, 0x2a, 0xb1, 0x3d, 0x69, 0xbb, 0xea, 0xbd, 0x51,
	0x55, 0x6f, 0xf6, 0x08, 0xb6, 0xcd, 0x3f, 0x5d, 0xfa, 0x55, 0xce, 0x14, 0x78, 0x33, 0xb1, 0x31,
	0xe9, 0x65, 0x4a, 0x7f, 0xa1, 0xd4, 0x17, 0x73, 0x99, 0x6a, 0x3c, 0x21, 0x62, 0x09, 0x9d, 0x66,
	0x93, 0x22, 0x91, 0x56, 0xd9, 0x93, 0x20, 0x19, 0x3a, 0xb3, 0xbd, 0x26, 0x98, 0x12, 0xe3, 0x1c,
	0x52, 0xa9, 0xcc, 0x65, 0xa0, 0x01, 0xec, 0x3b, 0xd0, 0x3e, 0x4a, 0xf5, 0xb3, 0xa7, 0xe8, 0xe8,
	0x44, 0x68, 0xe1, 0x76, 0x3f, 0x6c, 0x63, 0x61, 0x07, 0x2e, 0x2f, 0x06, 0xc5, 0xf8, 0xe9, 0x40,
	0xc5, 0x74, 0xac, 0xc5, 0xa4, 0xa2, 0x7a, 0x61, 0xf3, 0xb8, 0x14, 0x78, 0xb5, 0xb4, 0x75, 0x65,
	0x19, 0x6f, 0x7b, 0x65, 0x1c, 0x7f, 0x15, 0xba, 0x35, 0xd8, 0x3a, 0x6d, 0x11, 0xfa, 0x38, 0x8d,
	0x97, 0x71, 0x4a, 0x75, 0xa0, 0xcd, 0x0d, 0xc0, 0xa8, 0x67, 0x74, 0x7a, 0x9d, 0x89, 0x58, 0xd1,
	0xbd, 0xa2, 0xc3, 0x3d, 0x49, 0xe9, 0xa6, 0x8a, 0xbf, 0xd1, 0x6e, 0xfe, 0xc9, 0x73, 0xb3, 0x18,
	0x9b, 0x6a, 0x1e, 0xc9, 0x18, 0x6f, 0x52, 0x65, 0x35, 0x37, 0xb8, 0x1e, 0x42, 0xe3, 0xfa, 0x10,
	0x6e, 0xde, 0x30, 0xab, 0x10, 0xda, 0x57, 0x87, 0xb0, 0xe1, 0x85, 0xc0, 0xfe, 0x12, 0x60, 0xca,
	0x5d, 0x98, 0x9a, 0x87, 0xf7, 0xae, 0xfc, 0xff, 0xc3, 0xa6, 0x39, 0x14, 0x6d, 0xfa, 0x87, 0xa2,
	0x9b, 0xd8, 0xfc, 0x35, 0x9e, 0x15, 0x67, 0xc9, 0xca, 0x1e, 0x74, 0x06, 0xe7, 0x03, 0x11, 0x2b,
	0x3c, 0x10, 0xe7, 0x67, 0xd9, 0x62, 0x58, 0x44, 0x91, 0xcc, 0xf3, 0x93, 0x22, 0xb1, 0x37, 0x8d,
	0x35, 0xe9, 0x9a, 0xf5, 0xd6, 0x25, 0xeb, 0x2f, 0x68, 0x1b, 0x40, 0xdb, 0xfb, 0x22, 0x79, 0x8e,
	0x75, 0xda, 0x94, 0xd3, 0x6b, 0xce, 0x00, 0x44, 0x88, 0x2b, 0x71, 0x04, 0xd8, 0x2f, 0xe0, 0xae,
	0xef, 0x9f, 0x3b, 0x01, 0xec, 0x42, 0x37, 0x4b, 0x25, 0x9e, 0xdf, 0xfd, 0x6d, 0xc4, 0x13, 0x61,
	0x3d, 0x1a, 0x1b, 0x65, 0x77, 0xe4, 0xb4, 0x90, 0xfd, 0xb5, 0x01, 0xdb, 0xd6, 0xdc, 0xeb, 0x7d,
	0x73, 0x5b, 0xad, 0xae, 0xdb, 0x41, 0xed, 0xba, 0xfd, 0x9f, 0x25, 0xd0, 0x03, 0xd8, 0xca, 0x0a,
	0x7d, 0x54, 0xbe, 0x17, 0xb4, 0x79, 0x89, 0x71, 0xef, 0xd7, 0xcb, 0x41, 0x31, 0x4e, 0xe2, 0xe8,
	0xad, 0x5c, 0x71, 0x5a, 0xd9, 0x1e, 0xaf, 0xc9, 0xc2, 0xcf, 0x61, 0xc7, 0x46, 0x52, 0x0a, 0x69,
	0xad, 0x7b, 0xfc, 0x92, 0xbc, 0xda, 0x18, 0x36, 0xbd, 0x8d, 0xc1, 0x7b, 0xc6, 0xd8, 0xaa, 0x3d,
	0x63, 0xe0, 0x15, 0x68, 0x69, 0xca, 0x6b, 0x87, 0x1c, 0x73, 0xb0, 0x7c, 0xca, 0x20, 0x12, 0x80,
	0x26, 0xab, 0x04, 0xec, 0x3d, 0xb4, 0x30, 0x8d, 0xaf, 0x3b, 0xe8, 0x85, 0x4f, 0xa0, 0x53, 0xe8,
	0x65, 0xb6, 0x2f, 0xf2, 0x38, 0xb2, 0xcf, 0x2c, 0x3b, 0xde, 0xb3, 0x03, 0xc9, 0x79, 0xa5, 0xc2,
	0x66, 0xb0, 0x8d, 0xf2, 0x43, 0x31, 0x97, 0xa3, 0xa5, 0xbb, 0x1c, 0x5f, 0x69, 0x99, 0x56, 0x86,
	0x2e, 0xcd, 0xf6, 0x34, 0x60, 0x50, 0x7d, 0xc6, 0xe6, 0xcd, 0x33, 0x7e, 0x0e, 0x6d, 0xf3, 0x23,
	0x3e, 0x84, 0x36, 0x4a, 0xdd, 0x25, 0xb5, 0xf6, 0x3a, 0x62, 0x7a, 0x18, 0x87, 0xdb, 0x75, 0xef,
	0xf2, 0xf0, 0xe7, 0x70, 0x1b, 0xfb, 0x3c, 0xd1, 0xda, 0xfb, 0x48, 0x7d, 0x00, 0x5f, 0xd7, 0x66,
	0x27, 0x74, 0x27, 0x43, 0xad, 0x37, 0x49, 0x36, 0x16, 0xc9, 0x91, 0x63, 0xbd, 0xca, 0xaf, 0x60,
	0x3d, 0xbf, 0x70, 0x4f, 0x8e, 0x97, 0xaf, 0xbc, 0x9b, 0x4e, 0x89, 0x6b, 0xb9, 0xd7, 0xf4, 0x8e,
	0xdc, 0x39, 0x74, 0xca, 0xf8, 0xc3, 0x17, 0xc6, 0x6b, 0x6f, 0x46, 0x7b, 0xe2, 0xb8, 0xef, 0x79,
	0xed, 0xf5, 0xf2, 0x75, 0xf5, 0xf0, 0x13, 0xb8, 0x55, 0xa5, 0xdc, 0x79, 0xf9, 0x5a, 0x52, 0x17,
	0x32, 0x0e, 0x3b, 0x68, 0x89, 0x86, 0x3c, 0x7f, 0x39, 0x5d, 0x73, 0xb0, 0xbe, 0xa0, 0x8f, 0x1c,
	0xff, 0x0d, 0xe2, 0xef, 0xf2, 0xa2, 0xd9, 0x45, 0xf8, 0x6d, 0x80, 0x8c, 0xe5, 0xff, 0x3b, 0xc6,
	0x5e, 0xc1, 0x0e, 0x5a, 0xf6, 0x9d, 0x24, 0xee, 0xba, 0x4f, 0xbf, 0xe5, 0xf9, 0xe0, 0x77, 0xf3,
	0x4b, 0x03, 0x70, 0x8f, 0xbc, 0x73, 0x80, 0x79, 0x34, 0xc4, 0xcf, 0x51, 0xfa, 0x21, 0x95, 0xa3,
	0x9b, 0x9c, 0xaa, 0x0a, 0x76, 0xa3, 0x56, 0xb0, 0x3f, 0x06, 0xb0, 0x0f, 0x10, 0x43, 0x19, 0xd9,
	0x0b, 0xab, 0x27, 0xf1, 0x8a, 0x52, 0xcb, 0xa5, 0x3e, 0x15, 0xa5, 0x32, 0x83, 0xdb, 0xd7, 0x66,
	0xf0, 0x3f, 0x03, 0x2a, 0xbc, 0x66, 0x03, 0xf2, 0x6e, 0xd5, 0x37, 0x78, 0x1a, 0x42, 0x0b, 0x6d,
	0x59, 0xea, 0xa8, 0xfd, 0xb5, 0x76, 0x49, 0x77, 0x4d, 0x6d, 0x5f, 0xba, 0xa6, 0x6e, 0x94, 0xd7,
	0xd4, 0xfa, 0x96, 0x01, 0xeb, 0x5b, 0x86, 0x5d, 0x42, 0xb3, 0x93, 0x75, 0xcb, 0x25, 0x24, 0xcc,
	0x7e, 0x85, 0xe7, 0x50, 0x91, 0xbc, 0x95, 0xab, 0xa3, 0x74, 0x56, 0xd0, 0x4b, 0xaa, 0x92, 0x22,
	0x89, 0x11, 0xb8, 0x53, 0x6f, 0x9b, 0xd7, 0x64, 0xb8, 0x95, 0xd9, 0x64, 0xf5, 0x8f, 0xa7, 0x3d,
	0xbe, 0x26, 0x65, 0xcf, 0x01, 0xca, 0x1c, 0xcc, 0xab, 0x2c, 0x0d, 0xfe, 0x7d, 0x96, 0xfe, 0xa1,
	0x01, 0xf7, 0x2f, 0xb1, 0xfc, 0x4a, 0x44, 0x67, 0x12, 0x03, 0xa5, 0x0b, 0x22, 0xcd, 0x62, 0x7f,
	0x02, 0x4f, 0x82, 0x81, 0xe6, 0xf1, 0x69, 0x4a, 0xbd, 0x66, 0x87, 0x2a, 0x31, 0xa5, 0x0c, 0xbd,
	0xf8, 0xd9, 0xb4, 0xb0, 0x28, 0x7c, 0x0e, 0x5d, 0xef, 0x79, 0x9d, 0xb8, 0xbf, 0xfa, 0xe5, 0xdb,
	0x57, 0xbb, 0xf6, 0xf0, 0xf2, 0x63, 0x43, 0xdf, 0xb9, 0x5c, 0x11, 0x5b, 0xfd, 0x0d, 0x8a, 0xf5,
	0x6e, 0xf9, 0x3e, 0x5e, 0x31, 0xcd, 0x6b, 0x8a, 0xe1, 0x63, 0xc7, 0xce, 0x26, 0x8d, 0xb8, 0xb3,
	0xce, 0x4e, 0x6e, 0xe9, 0x19, 0x6f, 0xd0, 0xd3, 0xfd, 0xb3, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xa0, 0xec, 0xe3, 0xfb, 0x2a, 0x18, 0x00, 0x00,
}
