



cliCmd = "./chain33-cli"
checkSleepTime = 10
checkTimeout = 10


[[TestCaseFile]]
contract = "coins"
filename = "coins.toml"

[[TestCaseFile]]
contract = "token"
filename = "token.toml"

[[TestCaseFile]]
contract = "trade"
filename = "trade.toml"


[[TestCaseFile]]
contract = "privacy"
filename = "privacy.toml"

