


#chain33的客户端文件
cliCmd = "./chain33-cli"
#发送一笔交易后等待回执的超时时间，单位秒
checkTimeout = 60


[[TestCaseFile]]
dapp = "coins"
filename = "coins.toml"

[[TestCaseFile]]
dapp = "token"
filename = "token.toml"

[[TestCaseFile]]
dapp = "trade"
filename = "trade.toml"


[[TestCaseFile]]
dapp = "privacy"
filename = "privacy.toml"

