[[TokenPreCreateCase]]
id = "tokenPre"
command = "send token precreate -f 0.01 -i testToken -n testToken -s TC -a 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv -t 100000 -p 1 -k 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
dep = ["transForPrecreate"]

[[TokenPreCreateCase]]
id = "tokenPre2"
command = "send token precreate -f 0.01 -i testToken -n testToken -s TCC -a 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv -t 100000 -p 1 -k 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
dep = ["transForPrecreate"]


[[TokenFinishCreateCase]]
id = "tokenFinish"
command = "send token finish -a 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv -f 0.01 -s TC -k 0xc34b5d9d44ac7b754806f761d3d4d2c4fe5214f6b074c19f069c4f5c2a29c8cc"
dep = ["tokenPre"]


#send to token for precreate
[[TransferCase]]
id = "transForPrecreate"
command = "send bty transfer -a 10 -t 12hpJBHybh1mSyCijQ2MQJPk7z7kZ7jnQa -k 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
from = "12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
to = "12hpJBHybh1mSyCijQ2MQJPk7z7kZ7jnQa"
amount = "10"
checkItem = ["balance"]


[[TransferCase]]
id = "tokenTrans1"
command = "send token transfer -a 10 -s TC -t 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt -k 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
from = "12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
to = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
amount = "10"
checkItem = ["balance"]
repeat = 10
dep = ["tokenFinish"]



[[TransferCase]]
id = "tokenTrans2"
command = "send token transfer -a 10 -s TC -t 17UZr5eJVxDRW1gs7rausQwaSUPtvcpxGT -k 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
from = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
to = "17UZr5eJVxDRW1gs7rausQwaSUPtvcpxGT"
amount = "10"
checkItem = ["balance"]
dep = ["tokenTrans1"]


[[TransferCase]]
id = "failTokenTrans"       #带有fail前缀表示用例本身是失败的，在autotest程序中集成了这个特性
command = "send token transfer -a 101 -s TC -t 17UZr5eJVxDRW1gs7rausQwaSUPtvcpxGT -k 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
from = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
to = "17UZr5eJVxDRW1gs7rausQwaSUPtvcpxGT"
amount = "101"
checkItem = ["balance"]


#diposit to trade
[[TransferCase]]
id = "tokenDiposit1"
command = "send token transfer -a 10 -s TC -t 1BXvgjmBw1aBgmGn1hjfGyRkmN3krWpFP4 -k 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
from = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
to = "1BXvgjmBw1aBgmGn1hjfGyRkmN3krWpFP4"
amount = "10"
checkItem = ["balance"]
dep = ["tokenTrans1"]


[[WithdrawCase]]
id = "tokenWithdraw"
command = "send token withdraw -a 1 -s TC -e trade -k 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
addr = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
amount = "1"
checkItem = ["balance"]
dep = ["tokenDiposit1"]
repeat = 4


[[WithdrawCase]]
id = "failTokenWithDraw"            #带有fail前缀表示用例本身是失败的，在autotest程序中集成了这个特性
command = "send token withdraw -a 11 -s TC -e trade -k 1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
addr = "1D9xKRnLvV2zMtSxSx33ow1GF4pcbLcNRt"
amount = "11"
checkItem = ["balance"]


#--liugui 2018.9.19-- 
[[tokenRevokeCase]]
id = "tokenRevoke"
command = "send token revoke -f 0.01 -s TCC -a 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv -k 12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
dep = ["tokenPre2"]