Title="chain33"

[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/chain33.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 100
# 最多保存的历史日志文件个数
maxBackups = 50
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=false
singleMode=false

[p2p]
seeds=["192.168.3.29:13802","192.168.3.30:13802","192.168.3.13:13802","192.168.3.4:13802"]
enable=true
isSeed=true
serverStart=true
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=199
verMix=199
verMax=199

[rpc]
jrpcBindAddr="localhost:8801"
grpcBindAddr="localhost:8802"
whitlist=["127.0.0.1"]
[mempool]
poolCacheSize=10240
minTxFee=100000

[consensus]
name="pbft"
minerstart=false
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
genesisBlockTime=1514533394
hotkeyAddr="12qyocayNF7Lv6C9qW4avxs2E7U41fKSfv"
timeoutPropose=3000
timeoutProposeDelta=500
timeoutPrevote=1000
timeoutPrevoteDelta=500
timeoutPrecommit=1000
timeoutPrecommitDelta=500
timeoutCommit=1000
skipTimeoutCommit=false
createEmptyBlocks=false
createEmptyBlocksInterval=0
seeds=["192.168.3.4:46656","192.168.3.13:46656","192.168.3.29:46656","192.168.3.30:46656"]

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[localstore]
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=100000
driver="leveldb"
dbPath="datadir/wallet"
signType="secp256k1"

[exec]
