title = "relayd"

watch = true
pprof = true
trace = false
heartbeat33 =10
heartbeatBTC = 10
reconnectAttempts = 10

[chain33]
id = "123"
host = "localhost"
endpoint = "8802"
user = "123"
pass = "123"
disableAutoReconnect = true

[bitcoin]
id = "123abc"
host = "127.0.0.1"
endpoint = "8834"
user = ""
pass = ""
disableTLS = false
certPath = "/home/suyanlong/.btcd"
proxy = ""
proxyUser = ""
proxyPass = ""
disableAutoReconnect = true
disableConnectOnNew = false
HTTPPostMode = false
enableBCInfoHacks = false


[log]
# 日志级别，支持debug(dbug)/info/warn/error(eror)/crit
loglevel = "debug"
logConsoleLevel = "info"
# 日志文件名，可带目录，所有生成的日志文件都放到此目录下
logFile = "logs/relayd.log"
# 单个日志文件的最大值（单位：兆）
maxFileSize = 100
# 最多保存的历史日志文件个数
maxBackups = 50
# 最多保存的历史日志消息（单位：天）
maxAge = 28
# 日志文件名是否使用本地事件（否则使用UTC时间）
localTime = true
# 历史日志文件是否压缩（压缩格式为gz）
compress = true
# 是否打印调用源文件和行号
callerFile = false
# 是否打印调用方法
callerFunction = false

