
Title="chain33"

[blockchain]
defCacheSize=500
maxFetchBlockNum=100
timeoutSeconds=5
batchBlockNum=100
driver="leveldb"
dbPath="datadir"

[p2p]
seeds=["113.55.101.159:13802"]
isSeed=false
enable=false
seedPort=13802
dbPath="datadir/addrbook"

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="solo"
genesis="14KEKbYtKKQm4wMthSK9J4La4nAiidGozt"
minerstart=true

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
