Title="chain33"

Loglevel="debug"
LogConsoleLevel="info"
LogFile="chain33.log"

[blockchain]
defCacheSize=512
maxFetchBlockNum=128
timeoutSeconds=5
batchBlockNum=128
driver="leveldb"
dbPath="datadir"
isStrongConsistency=true
singleMode=true

[p2p]
seeds=["47.104.125.151:13802","47.104.125.97:13802","47.104.125.177:13802"]
enable=true
isSeed=true
msgCacheSize=10240
dbPath="datadir/addrbook"
grpcLogFile="grpc33.log"
version=216
verMix=216
verMax=217

[mempool]
poolCacheSize=10240
minTxFee=1000000

[consensus]
name="ticket"
minerstart=true

[store]
name="mavl"
driver="leveldb"
dbPath="datadir/mavltree"

[wallet]
minFee=1000000
dbPath="datadir/wallet"

[exec]
